import {MAGES,CARD_BY_ID} from './cards.js?v=0500';
export function validRemoteDeck(element,ids){if(!MAGES[element]||!Array.isArray(ids)||ids.length!==20)return false;const counts={};return ids.every(id=>{const c=CARD_BY_ID[id];return c&&!c.generated&&[element,'neutral'].includes(c.element)&&(counts[id]=(counts[id]||0)+1)<=2})}
export function validAction(a){if(!a||!['card','attack','move','power','end','surrender','legacy'].includes(a.type))return false;if(['card','legacy'].includes(a.type)&&(!Number.isInteger(a.index)||a.index<0||a.index>11))return false;if(['attack','move'].includes(a.type)&&(!Number.isInteger(a.lane)||a.lane<0||a.lane>2||!Number.isInteger(a.slot)||a.slot<0||a.slot>1))return false;if(a.type==='legacy'&&![0,1,2].includes(a.choice))return false;const t=a.target;if(['attack','move','power'].includes(a.type)&&!t)return false;if(t?.kind==='unit'&&![0,1].includes(t.slot))return false;if(t&&(![0,1].includes(t.side)||!['unit','crystal','rune'].includes(t.kind)||!Number.isInteger(t.lane)||t.lane<0||t.lane>2||![0,1,undefined].includes(t.slot)))return false;return true}
export const flipTarget=t=>t?{...t,side:1-t.side}:t;
export function guestView(duel,events=[]){const c=x=>JSON.parse(JSON.stringify(x));const own=c(duel.sides[1]),enemy=c(duel.sides[0]);enemy.hand=enemy.hand.map(()=>({hidden:true}));enemy.deck=enemy.deck.map(()=>({hidden:true}));own.deck=own.deck.map(()=>({hidden:true}));return {sides:[own,enemy],active:1-duel.active,round:duel.round,over:duel.over,winner:duel.winner==null?null:1-duel.winner,log:duel.log,events:events.map(e=>({...e,side:e.side===undefined?undefined:1-e.side,source:flipTarget(e.source),target:flipTarget(e.target),winner:e.winner===undefined?undefined:1-e.winner}))}}
export function validView(v){return v&&[0,1].includes(v.active)&&Array.isArray(v.sides)&&v.sides.length===2&&v.sides.every(s=>MAGES[s.element]&&Array.isArray(s.hand)&&s.hand.length<=12&&Array.isArray(s.deck)&&s.deck.length<=22&&Array.isArray(s.lanes)&&s.lanes.length===3&&s.lanes.every(l=>Array.isArray(l)&&l.length===2)&&Array.isArray(s.crystals)&&s.crystals.length===3&&Array.isArray(s.runes)&&s.runes.length===3)}
const ENCODE=x=>btoa(unescape(encodeURIComponent(JSON.stringify(x)))),DECODE=x=>JSON.parse(decodeURIComponent(escape(atob(x.trim()))));
export class PrivateLink{
 constructor(api){this.api=api;this.peer=null;this.conn=null;this.pc=null;this.state='Desconectado';this.online=false;this.host=false;this.accepted=false;this.timeout=null}
 status(s){this.state=s;this.api.status?.(s)}
 async enable(){if(this.online)return true;if(this.loading)return false;this.loading=true;this.status('Conectando al servicio de salas…');try{if(!window.Peer)await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=new URL('./peerjs.min.js',import.meta.url).href;s.onload=resolve;s.onerror=()=>reject(Error('No se pudo cargar el servicio de salas.'));document.head.append(s);setTimeout(()=>reject(Error('El servicio no respondió. Usa la conexión por códigos.')),12000)});this.peer?.destroy();this.peer=new window.Peer('crystal-'+this.api.profile.playerId,{debug:0});this.peer.on('connection',c=>{if(this.conn){c.close();return}this.bind(c,false)});this.peer.on('error',e=>{this.status(e.type==='unavailable-id'?'Este ID ya está abierto en otra pestaña.':e.type==='peer-unavailable'?'El rival no está conectado. Debe pulsar Conectarme.':'No se pudo conectar. Puedes usar códigos de red local.');this.online=false;this.loading=false});this.peer.on('disconnected',()=>{this.online=false;this.status('Servicio de salas desconectado')});return await new Promise(resolve=>{this.peer.on('open',()=>{this.online=true;this.loading=false;this.status('Disponible para desafíos');resolve(true)});setTimeout(()=>{if(!this.online){this.loading=false;this.status('No respondió el servicio. Usa códigos de red local.');resolve(false)}},12000)})}catch(e){this.loading=false;this.status(e.message);return false}}
 async challenge(id){if(!/^CD-[A-Z0-9]{6,12}$/.test(id)){this.status('Usa el ID CD-… de tu amigo. Una IP sola no abre una partida web.');return}if(id===this.api.profile.playerId){this.status('Ese es tu propio ID.');return}if(!validRemoteDeck(this.api.profile.selected,this.api.profile.decks[this.api.profile.selected])){this.status('Completa tu mazo de 20 cartas.');return}if(!await this.enable())return;this.disconnect(false);this.status('Buscando al rival…');this.bind(this.peer.connect('crystal-'+id,{reliable:true,serialization:'json'}),true)}
 payload(){const p=this.api.profile;return {name:p.name.slice(0,20),id:p.playerId,element:p.selected,deck:p.decks[p.selected]}}
 bind(c,host,local=false){this.conn=c;this.host=host;this.accepted=false;const whenOpen=()=>{clearTimeout(this.timeout);this.status(host?'Esperando aceptación del rival…':'Conexión privada abierta');if(host)this.send({type:'hello',player:this.payload()})};c.on('open',whenOpen);c.on('data',d=>this.receive(d));c.on('close',()=>{if(this.conn!==c)return;const was=this.accepted;this.conn=null;this.accepted=false;this.status('El rival se desconectó');if(was)this.api.disconnected?.()});c.on('error',()=>{const was=this.accepted;this.status('No se pudo establecer la conexión privada.');this.disconnect(false);if(was)this.api.disconnected?.()});this.timeout=setTimeout(()=>{if(this.conn===c&&!this.accepted){this.status('No hubo respuesta. Ambos deben estar conectados.');this.disconnect(false)}},local?300000:20000)}
 send(d){try{if(this.conn?.open){this.conn.send(d);return true}}catch{}return false}
 receive(d){if(!d||typeof d!=='object'||JSON.stringify(d).length>200000)return;if(d.type==='hello'&&!this.host&&!this.accepted){const p=d.player;if(!p||!validRemoteDeck(p.element,p.deck)){this.send({type:'reject'});return}this.api.invite(p,()=>{if(!validRemoteDeck(this.api.profile.selected,this.api.profile.decks[this.api.profile.selected])){this.status('Completa tu mazo antes de aceptar.');return}this.accepted=true;this.send({type:'accept',player:this.payload()});this.api.join?.(p);this.status('Duelo privado conectado')},()=>{this.send({type:'reject'});this.disconnect()});return}if(d.type==='accept'&&this.host&&!this.accepted){if(!d.player||!validRemoteDeck(d.player.element,d.player.deck))return;this.accepted=true;clearTimeout(this.timeout);this.status('Duelo privado conectado');this.api.host?.(d.player);return}if(d.type==='reject'){this.status('El rival rechazó el desafío.');this.disconnect(false);return}if(!this.accepted)return;this.api.data?.(d)}
 disconnect(update=true){const c=this.conn;this.conn=null;this.accepted=false;clearTimeout(this.timeout);try{c?.close();this.pc?.close()}catch{}this.pc=null;if(update)this.status(this.online?'Disponible para desafíos':'Desconectado')}
 async localCode(offerCode){this.disconnect(false);this.status('Preparando conexión de red local…');const pc=new RTCPeerConnection({iceServers:[]});this.pc=pc;pc.addEventListener('connectionstatechange',()=>{if(this.pc===pc&&pc.connectionState==='failed'){const was=this.accepted;this.disconnect(false);this.status('No se pudo abrir el canal entre dispositivos. Revisa la red de ambos.');if(was)this.api.disconnected?.()}});const host=!offerCode;const wrap=dc=>{const handlers={},c={get open(){return dc.readyState==='open'},send:d=>dc.send(JSON.stringify(d)),close:()=>dc.close(),on:(n,f)=>handlers[n]=f};dc.onopen=()=>handlers.open?.();dc.onclose=()=>handlers.close?.();dc.onerror=()=>handlers.error?.();dc.onmessage=e=>{try{if(e.data.length<=200000)handlers.data?.(JSON.parse(e.data))}catch{}};this.bind(c,host,true)};if(host){wrap(pc.createDataChannel('crystal-duel'));await pc.setLocalDescription(await pc.createOffer())}else{const d=DECODE(offerCode);if(d.v!==1||d.type!=='offer'||typeof d.sdp!=='string'||d.sdp.length>50000)throw Error('Código de invitación inválido.');pc.ondatachannel=e=>wrap(e.channel);await pc.setRemoteDescription({type:'offer',sdp:d.sdp});await pc.setLocalDescription(await pc.createAnswer())}await new Promise(resolve=>{if(pc.iceGatheringState==='complete')return resolve();pc.addEventListener('icegatheringstatechange',()=>{if(pc.iceGatheringState==='complete')resolve()});setTimeout(resolve,6000)});if(!/^a=candidate:/m.test(pc.localDescription.sdp)){this.disconnect(false);const message='Este navegador no ofrece conexión directa en esta red. Prueba desde Chrome en los dos celulares.';this.status(message);throw Error(message)}this.status(host?'Invitación lista: espera el código de respuesta.':'Respuesta lista: compártela con quien invitó.');return ENCODE({v:1,type:pc.localDescription.type,sdp:pc.localDescription.sdp})}
 async acceptCode(code){if(!this.pc)throw Error('Primero crea una invitación.');const d=DECODE(code);if(d.v!==1||d.type!=='answer'||typeof d.sdp!=='string'||d.sdp.length>50000)throw Error('Código de respuesta inválido.');await this.pc.setRemoteDescription({type:'answer',sdp:d.sdp});this.status('Estableciendo canal local…')}
}
