import {MAGES,ELEMENTS,CATALOG,CARD_BY_ID,KEYWORDS,RULES,VERSION,deckList,curve} from './cards.js';
import {Duel,targetKey} from './engine.js';
import {icon,portrait,figure,prism,runestone,runeColors,cardMarkup,kindNames} from './art.js';
import {Sound} from './audio.js';
import {initLobby} from './lobby.js';
import {loadProfile,saveProfile,validDeck,settle,opponent} from './progress.js';
import {PrivateLink,validAction,validView,guestView,flipTarget} from './network.js';
const $=id=>document.getElementById(id),duel=new Duel(),sound=new Sound();
let chosen='fire',selection=null,busy=false,match=0,toastTimer,announceTimer,installPrompt=null,collectionMode=false;
const profile=loadProfile(localStorage);let saveFailed=false,encounter=null,networkMatch=false,revision=0,remotePlayer=null,tutorialStep=-1,suppressClickUntil=0;
function save(){saveFailed=!saveProfile(profile,localStorage);if(saveFailed)toast('El navegador no permitió guardar el progreso.')}
const heavy=Object.fromEntries(Object.entries(MAGES).map(([k,m])=>[k,m.heavy]));
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fromKey=key=>{const [side,kind,lane,slot]=key.split('-');return {side:+side,kind,lane:+lane,slot:+slot}};
const clone=o=>JSON.parse(JSON.stringify(o));
function updateSound(){document.querySelectorAll('.sound-toggle').forEach(b=>{b.innerHTML=icon(sound.enabled?'sound':'mute');b.setAttribute('aria-label',sound.enabled?'Desactivar sonido':'Activar sonido');b.setAttribute('aria-pressed',String(sound.enabled))})}
document.addEventListener('pointerdown',()=>sound.unlock(),{passive:true});
document.querySelectorAll('.sound-toggle').forEach(b=>b.onclick=async()=>{await sound.unlock();sound.toggle();updateSound();if(sound.enabled)sound.play('rune',chosen)});
function toast(text){$('toast').textContent=text;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),2600)}
function announce(title,sub=''){clearTimeout(announceTimer);const el=$('announcement');el.innerHTML=`${escape(title)}${sub?`<small>${escape(sub)}</small>`:''}`;el.classList.remove('hidden');el.style.animation='none';void el.offsetWidth;el.style.animation='';announceTimer=setTimeout(()=>el.classList.add('hidden'),reduced?1000:1200)}
function openModal(html,onClose=null){$('modal').innerHTML=`<button class="round-button modal-close" id="closeModal" aria-label="Cerrar">${icon('close')}</button>${html}`;$('overlay').classList.remove('hidden');$('closeModal').onclick=()=>{closeModal();onClose?.()};$('closeModal').focus({preventScroll:true})}
function closeModal(){$('overlay').classList.add('hidden')}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();selection=null;if(duel.sides.length)render()}});
$('overlay').addEventListener('click',e=>{if(e.target===$('overlay'))closeModal()});
function renderMenu(){lobby.render();updateSound()}
function showRules(){openModal(`<h2>El libro del santuario</h2><p>Rompe un cristal lateral y después el núcleo para ganar.</p><ul class="rule-list"><li><b>Invocación:</b> toca una carta para ampliar sus detalles. Arrástrala a una casilla iluminada, o usa «Elegir destino» y toca la casilla.</li><li><b>Combate:</b> toca un aliado preparado y luego un enemigo de su carril. El daño entre esbirros es simultáneo. Cada aliado ataca una vez por turno.</li><li><b>Traslado:</b> mantén presionado un aliado y arrástralo a otro carril. Cuesta 1 maná, lo agota y solo se permite una vez por turno. Si ya atacó o está Congelado, no puede trasladarse.</li><li><b>Concentración:</b> las gemas transparentes anticipan el coste; «Quedarás con» muestra tu maná restante. Soltar fuera de un destino válido no gasta maná.</li><li><b>Runas:</b> una por cristal. Las bendiciones afectan a los dos aliados de ese carril; las maldiciones se colocan al rival. Reemplazar una runa termina su aura anterior.</li><li><b>Vínculo del núcleo:</b> los dos laterales lo protegen. Destruir un lateral permite atacarlo. Guardia impide el ataque directo al cristal de su carril.</li><li><b>Despertar:</b> el primer daño no letal a la vida del núcleo activa la habilidad del mago.</li><li><b>Poder de mago:</b> cuesta 1 maná y se usa una vez por turno; puedes arrastrarlo al objetivo.</li><li><b>Mazo:</b> exactamente 15 cartas, máximo 2 copias; cartas de tu clase y neutrales. Empiezas con 4 y robas al comenzar el turno. Al agotarse, la Fatiga hace daño creciente a tu núcleo.</li><li><b>Cementerio y Reanimar:</b> los esbirros derrotados quedan en el cementerio; ciertos efectos los devuelven a una casilla vacía.</li><li><b>Agotamiento:</b> un esbirro recién invocado espera hasta tu siguiente turno. Ímpetu permite atacar esbirros al entrar.</li><li><b>Quemadura:</b> daño al final de los próximos 3 turnos de su dueño. Renovarla reinicia la duración.</li><li><b>Congelado:</b> no puede atacar ni moverse durante 1 turno.</li><li><b>Debilitado:</b> pierde ataque durante el número de turnos indicado. Los aumentos temporales terminan al acabar tu turno.</li></ul><div class="keyword-definitions">${Object.entries(RULES).map(([k,t])=>`<p><b>${KEYWORDS[k]}:</b> ${t}</p>`).join('')}</div><h3>Los Despertares</h3>${Object.values(MAGES).map(m=>`<p><b>${m.name}:</b> ${m.awake}</p>`).join('')}<button class="primary" id="rulesDone">Entendido</button>`);$('rulesDone').onclick=closeModal}
function showCard(c,{unit=null,target=null,back=null}={}){const kws=(c.kw||[]).map(k=>`<div><b>${KEYWORDS[k]}:</b> ${RULES[k]}</div>`).join('');let current='';if(unit&&target){const st=duel.stats(target.side,target.lane,unit);const statuses=[unit.shield?`Barrera ${unit.shield}`:'',unit.freeze?'Congelado: 1 turno':'',unit.burn?.left>0?`Quemadura ${unit.burn.amount}: ${unit.burn.left} turnos`:'',unit.weak?.left>0?`−${unit.weak.amount} ATQ: ${unit.weak.left} turnos`:'',unit.focus?`+${unit.focus} ATQ hasta fin de turno`:''];current=`<p>En el campo: <b>${st.atk} ATQ · ${st.hp}/${st.max} VIDA</b><br>${statuses.filter(Boolean).join(' · ')}</p>`}openModal(`${cardMarkup(c,{large:true})}${current}<div class="keyword-definitions">${kws}${c.type==='rune'?'<div>La runa afecta a los dos esbirros de su cristal, incluidos los que invoques después. Sus efectos terminan al reemplazarla o destruir su cristal.</div>':''}</div><button id="cardBack" class="secondary">${back?'Volver al mazo':'Volver al tablero'}</button>`);$('cardBack').onclick=back||closeModal}
function selectedTargets(){if(!selection||duel.over||busy||duel.active!==0)return [];const s=duel.sides[0];if(selection.type==='card'){const c=s.hand[selection.index];return duel.canPlay(0,c)?duel.targets(0,c):[]}if(selection.type==='unit')return duel.attackTargets(0,selection.lane,selection.slot);if(selection.type==='move')return duel.moves(0,selection.lane,selection.slot);if(selection.type==='power'&&!s.powerUsed&&s.mana>=1)return duel.powerTargets(0);return []}
function renderBoard(p,id,targets){const s=duel.sides[p],m=MAGES[s.element];$(id).innerHTML=s.lanes.map((lane,l)=>{const rune=s.runes[l],c=s.crystals[l],color=rune?runeColors[rune.effect]:m.color;const runeKey=targetKey({side:p,kind:'rune',lane:l}),crystalKey=targetKey({side:p,kind:'crystal',lane:l});const runeTarget=targets.has(runeKey),crystalTarget=targets.has(crystalKey)||runeTarget;return `<div class="lane" data-lane="${l}" style="--rune:${color};--element:${m.color}"><div class="unit-pair">${lane.map((u,slot)=>{const t={side:p,kind:'unit',lane:l,slot},key=targetKey(t),selected=selection&&['unit','move'].includes(selection.type)&&p===0&&selection.lane===l&&selection.slot===slot;if(!u)return `<button class="slot empty ${targets.has(key)?'target':''}" data-target="${key}" aria-label="Casilla ${slot+1}, carril ${l+1}, ${p?'rival':'propia'}, vacía"></button>`;const st=duel.stats(p,l,u),kw=['guard','rush','overflow','lifesteal','burnHit','armorAtk','healFury'].filter(k=>duel.has(p,l,u,k));return `<button class="slot kind-${u.kind} ${p===0&&duel.ready(p,l,u)&&duel.active===0?'ready':''} ${selected?'selected':''} ${targets.has(key)?'target':''} ${u.freeze?'frozen':''} ${u.moved?'relocating':''}" data-target="${key}" data-unit="${u.uid}" aria-label="${escape(u.name)}, ${st.atk} ataque, ${st.hp} vida, carril ${l+1}, ${p?'rival':'propio'}"><span class="unit-base"></span><span class="standing">${figure(u)}</span><span class="unit-numbers"><b>${st.atk}</b><b class="hp">${st.hp}</b></span><span class="unit-status">${u.freeze||u.moved?icon('freeze'):''}${u.burn?.left>0?icon('fire'):''}${kw.slice(0,2).map(k=>icon(k==='guard'?'shield':k==='burnHit'?'fire':k)).join('')}</span>${u.shield?`<span class="shield-tag">${u.shield}</span>`:''}</button>`}).join('')}</div><button class="rune-button ${rune?'filled':'empty'} ${runeTarget?'target':''}" data-target="${runeKey}" aria-label="${rune?escape(rune.name):'Ranura de runa'}, carril ${l+1}, ${p?'rival':'propia'}">${rune?runestone(rune):icon('rune')}</button><button class="crystal-button ${l===1?'core':''} ${c.hp===0?'dead':''} ${rune?'enchanted':''} ${crystalTarget?'target':''} ${l===1&&!duel.accessible(p,1)?'locked-core':''}" ${p===1&&l===1&&!duel.accessible(p,1)?'disabled':''} data-target="${crystalKey}" aria-label="Cristal ${l===1?'central':l===0?'izquierdo':'derecho'} ${p?'rival':'propio'}, ${c.hp} de ${c.max} vida${rune?', '+escape(rune.name):''}">${l===1?`<span class="core-portrait">${portrait(s.element)}</span>`:''}${prism(color)}${l===1&&!duel.accessible(p,1)?'<span class="core-lock" aria-label="Núcleo protegido">'+icon('shield')+'</span>':''}<span class="crystal-label">${l===1?'NÚCLEO':l===0?'OESTE':'ESTE'}</span><span class="crystal-hp">${c.hp}<small> / ${c.max}</small></span>${c.shield?`<span class="crystal-shield">${icon('shield')}${c.shield}</span>`:''}</button></div>`}).join('')}
function render(){if(!duel.sides.length)return;const [s,e]=duel.sides,targets=new Set(selectedTargets().map(targetKey));$('app').style.setProperty('--element',MAGES[s.element].color);$('enemyPortrait').innerHTML=portrait(e.element);$('playerPortrait').innerHTML=portrait(s.element);$('enemyName').textContent=(encounter?.name||MAGES[e.element].name)+(e.awake?' · Despierto':'');$('playerName').textContent=MAGES[s.element].name+(s.awake?' · Despierto':'');$('enemyInfo').textContent=`${networkMatch?'Duelo privado':encounter?.label||MAGES[e.element].element} · Maná ${e.mana}/${e.maxMana} · Mazo ${e.deck.length}`;$('playerInfo').textContent=`${MAGES[s.element].element} · Mazo ${s.deck.length} · Caídos ${s.grave.length}`;$('roundLabel').innerHTML=`RONDA<strong>${duel.round}</strong>`;$('enemyHand').innerHTML=Array.from({length:e.hand.length},(_,i)=>`<span class="card-back" style="--tilt:${(i%5-2)*3}deg">◇</span>`).join('')+`<small>${e.hand.length} cartas</small>`;$('turnLabel').textContent=duel.over?'DUELO TERMINADO':duel.active===0?'TU TURNO':'TURNO DEL RIVAL';renderBoard(1,'enemyBoard',targets);renderBoard(0,'playerBoard',targets);
 const scroll=$('hand').scrollLeft;$('hand').innerHTML=s.hand.map((c,i)=>`<button class="hand-card ${duel.canPlay(0,c)&&!busy?'playable':''} ${c.cost>s.mana?'unaffordable':''} ${selection?.type==='card'&&selection.index===i?'selected':''}" data-hand="${i}" aria-label="${escape(c.name)}, ${c.cost} maná, ${kindNames[c.kind]}. ${escape(c.text)}">${cardMarkup(c)}</button>`).join('');$('hand').scrollLeft=scroll;
 const power=MAGES[s.element].power;$('powerButton').innerHTML=`${icon(s.element)}<span><b>${power.name}</b><small>${s.powerUsed?'Usado este turno':'Poder de mago'}</small></span><span class="mini-cost">1</span>`;$('powerButton').classList.toggle('selected',selection?.type==='power');$('powerButton').disabled=busy||duel.over||duel.active!==0||s.powerUsed||s.mana<1;$('powerButton').setAttribute('aria-label',`${power.name}, poder de 1 maná. ${power.text}${s.powerUsed?' Ya usado.':''}`);
 $('manaBar').innerHTML=`<div class="mana-pips">${Array.from({length:s.maxMana},(_,i)=>`<i class="mana-pip ${i>=s.mana?'spent':''}"></i>`).join('')}</div><span class="mana-count">${s.mana}<small> / ${s.maxMana}</small></span>`;renderManaPreview();$('endButton').disabled=busy||duel.over||duel.active!==0;$('endButton').innerHTML=duel.over?'Duelo terminado':duel.active===1?'Juega el rival…':'Terminar turno <span>›</span>';renderContext();updateSound();renderLift();renderGuide()}
function renderContext(){const s=duel.sides[0],c=selection?.type==='card'?s.hand[selection.index]:null;let text=duel.over?'El duelo ha terminado.':duel.active===1?'El rival está preparando su siguiente movimiento…':busy?'La magia toma forma…':`Tu mano · ${s.hand.length} cartas. Toca una carta y su destino.`;let actions='';if(c){text=`<b>${escape(c.name)}</b> · ${escape(c.text)}`;if(c.cost>s.mana)text=`<b>Necesitas ${c.cost} maná (${s.mana} disponible).</b> ${escape(c.name)}`;if(c.target==='none')actions+=`<button class="small-action" data-context="cast" ${!duel.canPlay(0,c)||busy?'disabled':''}>Lanzar</button>`}else if(selection?.type==='unit'){const u=s.lanes[selection.lane][selection.slot];if(u){const st=duel.stats(0,selection.lane,u);text=`<b>${escape(u.name)}</b> · ${st.atk} ATQ / ${st.hp} VIDA. ${duel.ready(0,selection.lane,u)?'Toca un enemigo iluminado.':'Descansa este turno.'}`;if(duel.moves(0,selection.lane,selection.slot).length)actions+=`<button class="icon-button" data-context="move" aria-label="Mover por 1 maná">${icon('move')}</button>`;actions+=`<button class="icon-button" data-context="details" aria-label="Ver esbirro">${icon('eye')}</button>`}}else if(selection?.type==='move')text='Traslado: 1 maná. El aliado quedará agotado hasta tu próximo turno.';else if(selection?.type==='power')text=`<b>${MAGES[s.element].power.name}</b> · ${MAGES[s.element].power.text} Toca un objetivo.`;if(selection)actions+=`<button class="icon-button" data-context="cancel" aria-label="Cancelar selección">${icon('close')}</button>`;$('contextText').innerHTML=text;$('contextActions').innerHTML=actions}
let lifted=false;
function clickHand(i){if(Date.now()<suppressClickUntil||duel.over||busy||duel.active!==0)return;selection={type:'card',index:i};lifted=true;sound.play('select',duel.sides[0].element);advanceGuide('select');render()}
$('hand').onclick=e=>{const b=e.target.closest('[data-hand]');if(b)clickHand(+b.dataset.hand)};
function renderLift(){const c=selection?.type==='card'?duel.sides[0].hand[selection.index]:null;const el=$('cardLift');el.classList.toggle('hidden',!c||!lifted||busy);if(!c||!lifted||busy)return;el.innerHTML=`<button id="closeLift" class="red-close" aria-label="Cerrar carta ampliada">‹</button><div data-lift-card="${selection.index}">${cardMarkup(c,{large:true})}</div><p class="lift-hint">Arrastra esta carta a un destino iluminado</p><button id="chooseTarget" class="primary">${c.target==='none'?'Lanzar hechizo':'Elegir destino'}</button>`;$('closeLift').onclick=()=>{selection=null;lifted=false;render()};$('chooseTarget').onclick=()=>{lifted=false;if(c.target==='none')perform({type:'card',index:selection.index});else render()}}
function plannedMana(){if(selection?.type==='card')return duel.sides[0].hand[selection.index]?.cost||0;return ['move','power'].includes(selection?.type)?1:0}
function renderManaPreview(){const s=duel.sides[0],cost=plannedMana();$('manaBar').querySelectorAll('.mana-pip').forEach((e,i)=>e.classList.toggle('will-spend',cost>0&&i<s.mana&&i>=s.mana-cost));if(cost){const tag=document.createElement('span');tag.className='mana-after'+(cost>s.mana?' insufficient':'');tag.innerHTML=cost>s.mana?`Faltan ${cost-s.mana}`:`−${cost} <b>Quedarás con ${s.mana-cost}</b>`;$('manaBar').append(tag)}}
function findTargetElement(t){return document.querySelector(`[data-target="${targetKey(t)}"]`)}
function locationOf(t){let el=t?findTargetElement(t):$('playerPortrait');if(!el)return null;const r=el.getBoundingClientRect(),app=$('app').getBoundingClientRect();return {x:r.left+r.width/2-app.left,y:r.top+r.height/2-app.top}}
function particle(kind,pos,tint,extra={}){if(!pos||reduced)return;const el=document.createElement('div');el.className='fx-'+kind;el.style.left=pos.x+'px';el.style.top=pos.y+'px';el.style.setProperty('--tint',tint);for(const [k,v] of Object.entries(extra))if(k==='text')el.textContent=v;else el.style.setProperty(k,v);$('fx').append(el);setTimeout(()=>el.remove(),1100)}
function burst(pos,color,n=13){particle('ring',pos,color);for(let i=0;i<n;i++){const angle=Math.PI*2*i/n,dist=24+Math.random()*43;particle('particle',pos,color,{'--dx':Math.cos(angle)*dist+'px','--dy':Math.sin(angle)*dist+'px'})}}
function bolt(from,to,color){if(!from||!to)return;particle('bolt',from,color,{'--dx':to.x-from.x+'px','--dy':to.y-from.y+'px'})}
function applyAction(p,a){if(!validAction(a))return false;try{if(a.type==='card')return duel.play(p,a.index,a.target);if(a.type==='attack')return duel.strike(p,a.lane,a.slot,a.target);if(a.type==='move')return duel.move(p,a.lane,a.slot,a.target);if(a.type==='power')return duel.usePower(p,a.target);if(a.type==='end')return duel.active===p&&duel.end();if(a.type==='surrender'){duel.over=true;duel.winner=1-p;return true}}catch{return false}return false}
async function perform(action){if(busy||duel.over||duel.active!==0)return;lifted=false;busy=true;const token=match;await sound.unlock();if(token!==match)return;if(networkMatch&&!link.host){if(!link.send({type:'action',action,revision})){busy=false;toast('La conexión no está disponible.')}render();return}if(!applyAction(0,action)){busy=false;toast('Ese movimiento no está disponible.');render();return}advanceGuide(action.type,action);selection=null;const events=duel.drainEvents();render();await animate(events);if(token!==match)return;if(networkMatch)sendState(events);if(action.type==='end'&&!networkMatch&&!duel.over){await enemyTurn(token);return}busy=false;if(duel.over)showResult();else render()}
async function animate(events){const soundKinds=new Set();for(const ev of events){const target=ev.target,pos=locationOf(target),color=ELEMENTS[ev.element||duel.sides[target?.side||0].element]?.color||'#e8d8a5';
  if(['summon','rune','spell','power','attack','awaken','shatter','death','heal','shield'].includes(ev.type)&&!soundKinds.has(ev.type)){sound.play(ev.type,ev.element||duel.sides[target?.side||0].element,ev.card?.cost>=8);soundKinds.add(ev.type)}
  switch(ev.type){case 'summon':burst(pos,color,ev.card.cost>=8?22:13);{const el=findTargetElement(target)?.querySelector('.standing');if(el&&!reduced)el.animate([{opacity:0,transform:'translateY(22px) scale(.45)',filter:'brightness(2)'},{opacity:1,transform:'translateY(0) scale(1)',filter:'brightness(1)'}],{duration:420,easing:'cubic-bezier(.12,.8,.3,1.3)'})}break;
  case 'attack':{const source=locationOf(ev.source);bolt(source,pos,color);particle('slash',pos,color);const el=findTargetElement(ev.source);if(el&&source&&pos&&!reduced)el.animate([{transform:'translate(0,0)'},{transform:`translate(${(pos.x-source.x)*.25}px,${(pos.y-source.y)*.25}px) scale(1.12)`,offset:.35},{transform:'translate(0,0)'}],{duration:300,easing:'ease-out'});break}
  case 'spell':case 'power':bolt(locationOf(duel.core(ev.side??0)),pos||locationOf(duel.core(1)),color);burst(pos||locationOf(duel.core(1)),color);break;
  case 'rune':burst(locationOf({...target,kind:'crystal'}),runeColors[duel.sides[target.side].runes[target.lane]?.effect]||color,20);break;
  case 'damage':if(ev.amount)particle('number',pos,'#ffe3cf',{text:'−'+ev.amount});else if(ev.blocked)particle('number',pos,'#b5eafb',{text:'Barrera'});break;
  case 'heal':particle('number',pos,'#b6efc3',{text:'+'+ev.amount});break;
  case 'shield':particle('number',pos,'#afe7f3',{text:'+'+ev.amount});break;
  case 'death':case 'shatter':burst(pos,color,18);break;
  case 'awaken':announce(`${MAGES[ev.element].name} despierta`,'EL PODER DEL NÚCLEO');burst(locationOf(duel.core(ev.side)),color,24);break;
  case 'turn':if(ev.side===0){sound.play('turn',duel.sides[0].element);announce('Tu turno',`RONDA ${ev.round}`)}break;
  case 'draw':if(!soundKinds.has('draw')&&ev.side===0){sound.play('draw',duel.sides[0].element);soundKinds.add('draw')}break;
  case 'overflow':particle('number',pos,'#ffd899',{text:'Desborde'});break;
  }
 }await delay(reduced?80:events.some(e=>e.type==='awaken')?780:events.some(e=>['spell','summon','rune','attack','power'].includes(e.type))?430:180)}
function clickTarget(t){if(Date.now()<suppressClickUntil||busy||duel.over||duel.active!==0)return;lifted=false;const ts=selectedTargets();let valid=ts.find(x=>targetKey(x)===targetKey(t));if(!valid&&['card','power'].includes(selection?.type))valid=ts.find(x=>x.side===t.side&&x.lane===t.lane&&x.kind==='rune');if(valid){if(selection.type==='card'){const i=selection.index;return perform({type:'card',index:i,target:valid})}if(selection.type==='unit'){const {lane,slot}=selection;return perform({type:'attack',lane,slot,target:valid})}if(selection.type==='move'){const {lane,slot}=selection;return perform({type:'move',lane,slot,target:valid})}if(selection.type==='power')return perform({type:'power',target:valid})}
 if(selection&&selection.type!=='unit'){toast('Elige un objetivo iluminado, o cancela la selección.');return}const s=duel.sides[t.side],u=t.kind==='unit'?s.lanes[t.lane][t.slot]:null;if(u&&t.side===0){selection={type:'unit',lane:t.lane,slot:t.slot};sound.play('select',s.element);render()}else if(u)showCard(u.printed,{unit:u,target:t});else if(t.kind==='rune'&&s.runes[t.lane])showCard(s.runes[t.lane]);else if(t.kind==='crystal'){const c=s.crystals[t.lane];toast(`${t.lane===1?'Núcleo':'Cristal'}: ${c.hp}/${c.max} vida${s.runes[t.lane]?' · '+s.runes[t.lane].name:''}. ${t.lane===1&&!duel.accessible(t.side,1)?'Destruye primero un lateral.':''}`)}}
for(const id of ['playerBoard','enemyBoard'])$(id).onclick=e=>{const b=e.target.closest('[data-target]');if(b)clickTarget(fromKey(b.dataset.target))};
$('contextActions').onclick=e=>{const b=e.target.closest('[data-context]');if(!b||Date.now()<suppressClickUntil)return;const action=b.dataset.context;if(action==='cancel'){selection=null;render()}else if(action==='move'){selection={...selection,type:'move'};render()}else if(action==='cast'&&selection?.type==='card'){const i=selection.index;perform({type:'card',index:i})}else if(action==='details'){if(selection?.type==='card')showCard(duel.sides[0].hand[selection.index]);else if(selection?.type==='unit'){const t={side:0,kind:'unit',lane:selection.lane,slot:selection.slot},u=duel.sides[0].lanes[t.lane][t.slot];if(u)showCard(u.printed,{unit:u,target:t})}}};
$('powerButton').onclick=()=>{lifted=false;if(Date.now()<suppressClickUntil||busy||duel.active!==0||duel.over)return;if(!duel.powerTargets(0).length){toast('No hay objetivos disponibles para tu poder.');return}selection=selection?.type==='power'?null:{type:'power'};sound.play('select',duel.sides[0].element);render()};
async function enemyTurn(token){let guard=0;while(duel.active===1&&!duel.over&&token===match&&guard++<40){if(!$('overlay').classList.contains('hidden')){await delay(250);guard--;continue}const action=duel.aiChoice();if(!action)break;duel.act(action);const events=duel.drainEvents();render();await animate(events);await delay(reduced?50:180)}if(token!==match)return;if(!duel.over)duel.end();const events=duel.drainEvents();render();await animate(events);if(token!==match)return;busy=false;if(duel.over)showResult();else render()}
$('endButton').onclick=()=>perform({type:'end'});
async function start(options={}){if(busy)return;if(!validDeck(profile)){toast('Completa un mazo de 15 cartas.');return}busy=true;await sound.unlock();match++;selection=null;lifted=false;networkMatch=false;link.disconnect();chosen=profile.selected;encounter=opponent(profile,options);duel.start(chosen,8,{foe:encounter.element,playerDeck:profile.decks[chosen].map(id=>CARD_BY_ID[id]),enemyDeck:encounter.deck,aiLevel:encounter.level,tutorial:options.tutorial});if(options.tutorial){tutorialStep=0;setupTutorial()}else tutorialStep=-1;closeModal();$('menu').classList.add('hidden');$('game').classList.remove('hidden');$('battlefield').scrollTop=0;busy=false;render();sound.play('start',chosen);if(!options.tutorial)announce(encounter.boss?'Desafío de guardián':'Que comience el duelo',encounter.name);duel.drainEvents()}
function showResult(){busy=false;selection=null;lifted=false;render();const win=duel.winner===0;const reward=networkMatch?{practice:true,trophies:0,coins:0,gems:0}:settle(profile,encounter.id,win,encounter);save();sound.play(win?'victory':'shatter',duel.sides[0].element);openModal(`<div class="victory-art">${prism(win?'#e9cf82':'#9eafbd')}</div><h2>${win?'¡Victoria!':'Tu núcleo se ha quebrado'}</h2><p>Ronda ${duel.round} · ${encounter.name}</p>${reward?reward.practice?'<p>Partida amistosa · Sin cambios en tus recursos.</p>':`<div class="result-rewards"><b>+${reward.trophies} trofeos</b><span>+${reward.coins} monedas · +${reward.gems} gemas</span></div>${reward.unlocked?`<div class="unlocked-hero">${portrait(reward.unlocked)}<h3>¡${MAGES[reward.unlocked].name} desbloqueado!</h3><p>Su mago, su mazo y sus cartas ya están en tu colección.</p></div>`:''}`:'<p>La recompensa ya está guardada.</p>'}<div class="modal-actions"><button id="backArena" class="battle-button">Volver a la arena</button></div>`,toMenu);$('backArena').onclick=toMenu}
function toMenu(){if(networkMatch)link.disconnect();networkMatch=false;match++;busy=false;selection=null;lifted=false;tutorialStep=-1;closeModal();$('cardLift').classList.add('hidden');$('guide').classList.add('hidden');$('game').classList.add('hidden');$('menu').classList.remove('hidden');renderMenu()}
$('menuGame').onclick=()=>{openModal(`<h2>El santuario</h2><p>${MAGES[duel.sides[0].element].name} · Ronda ${duel.round}</p><div class="volume-row"><span>Volumen</span><input id="volume" aria-label="Volumen de efectos" type="range" min="0" max="0.7" step="0.05" value="${sound.volume}"></div><div class="modal-actions"><button id="resume" class="primary">Continuar</button><button id="rulesGame" class="secondary">Reglas</button></div><div class="modal-actions"><button id="viewLog" class="secondary">Ver registro</button><button id="leaveGame" class="secondary">Salir del duelo</button></div>`);$('volume').oninput=e=>sound.setVolume(+e.target.value);$('resume').onclick=closeModal;$('rulesGame').onclick=showRules;$('viewLog').onclick=()=>openModal(`<h2>Memoria del duelo</h2><div class="log-entries">${duel.log.map(x=>`<p>${escape(x)}</p>`).join('')}</div>`);$('leaveGame').onclick=()=>{openModal(`<h2>¿Abandonar el duelo?</h2><p>Esta partida terminará y volverás a elegir mago.</p><div class="modal-actions"><button id="keepPlaying" class="primary">Seguir jugando</button><button id="confirmLeave" class="secondary">Abandonar</button></div>`);$('keepPlaying').onclick=closeModal;$('confirmLeave').onclick=toMenu}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});
if('serviceWorker' in navigator&&!location.pathname.includes('/v04/'))window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
const GUIDE=[['Invocación','Toca el Aprendiz de tu mano para ampliar su carta.'],['Invocación','Arrastra el Aprendiz a una de tus seis casillas. También puedes elegir el destino tocándolo.'],['Ritmo de turno','El esbirro espera antes de atacar. Pulsa Terminar turno para recuperar y aumentar el maná.'],['Combate y vínculo','Toca tu esbirro y ataca el cristal lateral iluminado. El núcleo permanece detrás, protegido.'],['Poder de mago','Usa Chispa viva sobre el constructo enemigo. Cuesta 1 maná y solo puede usarse una vez por turno.'],['Runas','Cuando tengas 3 manás, coloca Sello del ariete en un cristal tuyo. Su aura otorga Desborde a ambos aliados.'],['Traslado y agotamiento','En un turno nuevo, mantén presionado un aliado que no haya atacado y arrástralo a otro carril. Cuesta 1 maná y ya no podrá atacar este turno.'],['El núcleo te espera','¡Ya conoces lo esencial! Rompe un lateral, traslada tus aliados al centro y, en el turno siguiente, ataca el núcleo. Consulta el glosario desde el menú.']];
function setupTutorial(){chosen='fire';const ids=[0,2,5,6,7].map(i=>CATALOG.fire[i].id),all=deckList('fire');for(const id of ids){const i=all.findIndex(c=>c.id===id);if(i>=0)all.splice(i,1)}duel.sides[0].element='fire';duel.sides[0].hand=ids.map(id=>clone(CARD_BY_ID[id]));duel.sides[0].deck=all;duel.sides[1].crystals.forEach((c,i)=>{c.hp=c.max=i===1?12:5});duel.summon(1,{...clone(CATALOG.wind[2]),name:'Constructo de práctica',atk:0,hp:4,kw:[],entry:null},{side:1,kind:'unit',lane:2,slot:0},false)}
function advanceGuide(type,action){if(tutorialStep<0)return;const expected=['select','card','end','attack','power','card','move'];if(expected[tutorialStep]!==type)return;if(type==='card'){const c=duel.sides[0].lanes.flat().filter(Boolean);if(tutorialStep===1&&!c.length)return;if(tutorialStep===5&&!duel.sides[0].runes.some(Boolean))return}tutorialStep++;if(tutorialStep===7&&!encounter.practice){profile.tutorial=true;save()}}
function renderGuide(){const el=$('guide');el.classList.toggle('hidden',tutorialStep<0||duel.over||$('game').classList.contains('hidden'));document.querySelectorAll('.guide-target').forEach(e=>e.classList.remove('guide-target'));if(tutorialStep<0||duel.over)return;const [title,text]=GUIDE[Math.min(tutorialStep,7)];el.innerHTML=`<span class="guide-number">${tutorialStep+1}/8</span><div><b>${title}</b><p>${text}</p></div><button id="hideGuide" aria-label="Cerrar guía">×</button>`;$('hideGuide').onclick=()=>{tutorialStep=-1;if(!encounter.practice){profile.tutorial=true;save()}el.classList.add('hidden')};if(tutorialStep===0)$('hand').firstElementChild?.classList.add('guide-target');if(tutorialStep===2)$('endButton').classList.add('guide-target');if(tutorialStep===4)$('powerButton').classList.add('guide-target')}
let pointer=null,holdTimer=null;
function startDrag(){const g=pointer;if(!g||busy||duel.active!==0)return;if(g.origin==='unit'){const u=duel.sides[0].lanes[g.lane]?.[g.slot];if(!u||!duel.moves(0,g.lane,g.slot).length){toast(u?.attacked?'Ya atacó o se trasladó: espera a tu próximo turno.':'No puede trasladarse ahora. Necesitas 1 maná y una casilla libre.');pointer=null;return}selection={type:'move',lane:g.lane,slot:g.slot};g.art=figure(u)}else if(g.origin==='power'){if(duel.sides[0].powerUsed||duel.sides[0].mana<1)return;selection={type:'power'};g.art=icon(duel.sides[0].element)}else{selection={type:'card',index:g.index};const c=duel.sides[0].hand[g.index];if(!c)return;g.art=cardMarkup(c);advanceGuide('select')}g.drag=true;try{$('app').setPointerCapture(g.id)}catch{}lifted=false;render();$('dragGhost').innerHTML=g.art;$('dragGhost').classList.remove('hidden');$('dragGhost').classList.toggle('drag-unit',g.origin==='unit');$('dragGhost').classList.toggle('drag-power',g.origin==='power');moveGhost(g.x,g.y);sound.play('select',chosen);if(navigator.vibrate)navigator.vibrate(10)}
function moveGhost(x,y){const a=$('app').getBoundingClientRect();$('dragGhost').style.left=x-a.left+'px';$('dragGhost').style.top=y-a.top+'px';document.querySelectorAll('.drop-hover').forEach(e=>e.classList.remove('drop-hover'));const b=document.elementFromPoint(x,y)?.closest('[data-target]');if(b?.classList.contains('target'))b.classList.add('drop-hover')}
$('app').addEventListener('pointerdown',e=>{if(e.button!==0||$('game').classList.contains('hidden')||busy||duel.over||duel.active!==0||!$('overlay').classList.contains('hidden'))return;const card=e.target.closest('[data-hand],[data-lift-card]'),unit=e.target.closest('#playerBoard [data-unit]'),power=e.target.closest('#powerButton');if(!card&&!unit&&!power)return;const t=unit?fromKey(unit.dataset.target):{};pointer={id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,origin:card?'card':unit?'unit':'power',index:card?+(card.dataset.hand??card.dataset.liftCard):null,lane:t.lane,slot:t.slot,scroll:$('hand').scrollLeft,fromHand:!!card?.hasAttribute('data-hand'),drag:false};if(unit)holdTimer=setTimeout(startDrag,280);if(card&&!pointer.fromHand)holdTimer=setTimeout(startDrag,230)});
$('app').addEventListener('pointermove',e=>{const g=pointer;if(!g||g.id!==e.pointerId)return;g.x=e.clientX;g.y=e.clientY;const dx=g.x-g.startX,dy=g.y-g.startY;if(g.scrolling){$('hand').scrollLeft=g.scroll-dx;return}if(!g.drag&&g.fromHand&&Math.abs(dx)>12&&Math.abs(dx)>Math.abs(dy)*1.3){g.scrolling=true;clearTimeout(holdTimer);$('hand').scrollLeft=g.scroll-dx;return}if(!g.drag&&Math.hypot(dx,dy)>12){if(g.origin==='unit'){clearTimeout(holdTimer);startDrag()}else startDrag()}if(g.drag){e.preventDefault();moveGhost(g.x,g.y)}},{passive:false});
$('app').addEventListener('pointerup',e=>{const g=pointer;if(!g||g.id!==e.pointerId)return;clearTimeout(holdTimer);pointer=null;try{$('app').releasePointerCapture(e.pointerId)}catch{}if(g.scrolling){suppressClickUntil=Date.now()+350;return}if(!g.drag)return;suppressClickUntil=Date.now()+350;$('dragGhost').classList.add('hidden');document.querySelectorAll('.drop-hover').forEach(e=>e.classList.remove('drop-hover'));const b=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-target]'),t=b?fromKey(b.dataset.target):null,ts=selectedTargets();let valid=t&&ts.find(x=>targetKey(x)===targetKey(t));if(!valid&&t&&selection?.type==='card')valid=ts.find(x=>x.side===t.side&&x.lane===t.lane&&x.kind==='rune');if(g.origin==='card'){const c=duel.sides[0].hand[g.index];if(c?.target==='none'&&e.clientY<$('hand').getBoundingClientRect().top&&duel.canPlay(0,c))return perform({type:'card',index:g.index});if(valid)return perform({type:'card',index:g.index,target:valid})}else if(g.origin==='unit'&&valid)return perform({type:'move',lane:g.lane,slot:g.slot,target:valid});else if(g.origin==='power'&&valid)return perform({type:'power',target:valid});selection=null;render();toast('Sin destino válido. No se gastó maná.')});
$('app').addEventListener('pointercancel',()=>{clearTimeout(holdTimer);if(!pointer)return;pointer=null;$('dragGhost').classList.add('hidden');selection=null;lifted=false;render()});
const EMOTES=['Hola, ¡buenos días!','¡Prepárate para mi magia!','Muchas gracias','Buena partida'];let lastEmote=0;
function say(text,remote=false){$('emoteBubble').textContent=text;$('emoteBubble').classList.remove('hidden');$('emoteBubble').classList.toggle('from-enemy',remote);setTimeout(()=>$('emoteBubble').classList.add('hidden'),2400);if(sound.enabled&&'speechSynthesis' in window){speechSynthesis.cancel();const speech=new SpeechSynthesisUtterance(text);speech.lang='es-ES';speech.volume=Math.min(.65,sound.volume);speech.rate=1;speechSynthesis.speak(speech)}}
function heroMenu(){openModal(`<h2>${MAGES[duel.sides[0].element].name}</h2><div class="emote-grid">${EMOTES.map((text,i)=>`<button class="secondary" data-emote="${i}">${text}</button>`).join('')}<button id="surrender" class="secondary">Me rindo</button></div>`);$('modal').querySelectorAll('[data-emote]').forEach(b=>b.onclick=()=>{if(Date.now()-lastEmote<1800)return;lastEmote=Date.now();closeModal();const index=+b.dataset.emote;say(EMOTES[index]);if(networkMatch)link.send({type:'emote',index})});$('surrender').onclick=()=>{openModal('<h2>¿Rendirte?</h2><p>El duelo terminará con victoria del rival.</p><button id="confirmSurrender" class="battle-button">Confirmar rendición</button>');$('confirmSurrender').onclick=()=>{closeModal();if(networkMatch&&!link.host){link.send({type:'action',action:{type:'surrender'},revision});busy=true;return}applyAction(0,{type:'surrender'});if(networkMatch)sendState([]);showResult()}}}
$('playerPortrait').setAttribute('role','button');$('playerPortrait').setAttribute('tabindex','0');$('playerPortrait').setAttribute('aria-label','Frases de tu héroe');$('playerPortrait').onclick=heroMenu;$('playerPortrait').onkeydown=e=>{if(e.key==='Enter'||e.key===' ')heroMenu()};
const lobby=initLobby({profile,save,sound,start,open:openModal,close:closeModal,rules:showRules,notify:toast,saveFailed:()=>saveFailed,install:b=>{if(installPrompt){b.classList.remove('hidden');b.onclick=async()=>{await installPrompt.prompt();installPrompt=null;b.classList.add('hidden')}}}});
const link=new PrivateLink({profile,status:text=>{const el=$('connectionStatus');if(el)el.textContent=text},invite:(p,accept,reject)=>{if(!$('game').classList.contains('hidden')){reject();return}openModal(`<h2>Desafío privado</h2><p>${escape(p.name||'Un viajero')} te invita a un duelo con ${MAGES[p.element].name}.</p><button id="acceptChallenge" class="battle-button">Aceptar desafío</button><button id="rejectChallenge" class="secondary">Rechazar</button>`,reject);$('acceptChallenge').onclick=()=>{closeModal();accept()};$('rejectChallenge').onclick=()=>{closeModal();reject()}},host:beginPrivate,join:p=>{remotePlayer=p;networkMatch=true;revision=-1;encounter={id:'private',practice:true,name:p.name||'Rival',label:'Duelo privado'};toast('Desafío aceptado. Preparando tablero…')},data:receivePrivate,disconnected:()=>{if(!networkMatch)return;busy=true;openModal('<h2>Conexión interrumpida</h2><p>El duelo privado terminó sin cambiar tus trofeos ni tus recursos.</p><button id="exitPrivate" class="battle-button">Volver al inicio</button>',toMenu);$('exitPrivate').onclick=toMenu}});
function beginPrivate(p){remotePlayer=p;networkMatch=true;revision=0;match++;selection=null;lifted=false;tutorialStep=-1;chosen=profile.selected;encounter={id:'private',practice:true,name:p.name||'Rival',label:'Duelo privado'};duel.start(chosen,8,{foe:p.element,playerDeck:profile.decks[chosen].map(id=>CARD_BY_ID[id]),enemyDeck:p.deck.map(id=>CARD_BY_ID[id])});busy=false;closeModal();$('menu').classList.add('hidden');$('game').classList.remove('hidden');render();sendState(duel.drainEvents());announce('Duelo privado',encounter.name)}
function sendState(events){revision++;link.send({type:'state',revision,state:guestView(duel,events)})}
async function receivePrivate(d){if(!networkMatch)return;if(d.type==='emote'&&Number.isInteger(d.index)&&EMOTES[d.index]){if(Date.now()-lastEmote>1800){lastEmote=Date.now();say(EMOTES[d.index],true)}return}if(d.type==='action'&&link.host){if(busy||!validAction(d.action)||d.revision!==revision||duel.over||duel.active!==1&&d.action.type!=='surrender'){sendState([]);return}const a={...d.action,target:flipTarget(d.action.target)};busy=true;if(!applyAction(1,a)){busy=false;sendState([]);return}const ev=duel.drainEvents(),token=match;render();await animate(ev);if(token!==match)return;busy=false;sendState(ev);if(duel.over)showResult();else render();return}if(d.type==='state'&&!link.host&&Number.isInteger(d.revision)&&d.revision>revision&&validView(d.state)){revision=d.revision;const v=d.state;duel.sides=v.sides;duel.active=v.active;duel.round=v.round;duel.over=!!v.over;duel.winner=v.winner;duel.log=Array.isArray(v.log)?v.log.slice(0,60):[];selection=null;lifted=false;tutorialStep=-1;$('menu').classList.add('hidden');$('game').classList.remove('hidden');busy=true;render();await animate(Array.isArray(v.events)?v.events:[]);busy=false;if(duel.over)showResult();else render()}}
import('./friends.js').then(m=>m.initFriends({profile,link,open:openModal,close:closeModal,save,notify:toast,lobby}));
save();updateSound();
