import {MAGES,CATALOG,NEUTRALS,CARD_BY_ID,deckList} from './cards.js?v=0402';
export const SAVE_KEY='crystal-duel-campaign-v1';
export const BOSSES=[{at:300,element:'water',name:'Neris · La puerta de las mareas',unlock:'water'},{at:600,element:'wind',name:'Aeral · La aguja del viento',unlock:'wind'},{at:900,element:'light',name:'Solenne · El juramento del alba',unlock:'light'},{at:1200,element:'dark',name:'Morvane · El último sello',unlock:'dark'},{at:2500,element:'fire',name:'Pyra · La prueba del volcán'},{at:5000,element:'water',name:'Neris · El océano estelar'},{at:7500,element:'light',name:'Solenne · El sol eterno'},{at:10000,element:'dark',name:'Morvane · La corona del Umbral'}];
export const MILESTONES=[...Array.from({length:8},(_,i)=>(i+1)*150),1500,2000,2500,3000,3500,4000,4500,5000,5500,6000,6500,7000,7500,8000,8500,9000,9500,10000].map((at,i)=>({at,coins:100+(i>7?100:0),gems:10,card:NEUTRALS[i%NEUTRALS.length].id,count:2}));
export const OFFERS=[{id:'welcome',name:'Cofre del viajero',currency:'coins',cost:0,cards:['neutral-0','neutral-1'],color:'#63c8fc',label:'Regalo de bienvenida'},{id:'stone',name:'Cofre de piedra',currency:'coins',cost:150,cards:['neutral-2','neutral-3'],color:'#90b7cd',label:'Defiende tus carriles'},{id:'arcane',name:'Cofre arcano',currency:'coins',cost:300,cards:['neutral-4','neutral-5'],color:'#dd89ed',label:'Hechizo + runa'},{id:'sky',name:'Cofre del cielo',currency:'gems',cost:40,cards:['neutral-7','neutral-8'],color:'#67e1c2',label:'Robo + Ímpetu'}];
const clone=x=>JSON.parse(JSON.stringify(x));
const int=(n,max=999999)=>Math.max(0,Math.min(max,Math.floor(Number(n)||0)));
export const maxCopies=c=>2;
export function freshProfile(){const p={version:1,name:'Viajero',trophies:0,coins:200,gems:20,unlocked:['fire'],selected:'fire',owned:{},decks:{},claimed:[],purchases:[],beaten:[],settled:[],tutorial:false,wins:0,battles:0,sort:'type',playerId:'CD-'+Math.random().toString(36).slice(2,10).toUpperCase(),friends:[]};unlock(p,'fire');return p}
export function unlock(p,element){if(!p.unlocked.includes(element))p.unlocked.push(element);for(const c of CATALOG[element])p.owned[c.id]=maxCopies(c);p.decks[element]??=deckList(element).map(c=>c.id)}
export function validDeck(p,element=p.selected){const d=p.decks[element]||[];if(!p.unlocked.includes(element)||d.length!==15)return false;return d.every(id=>{const c=CARD_BY_ID[id];return c&&(c.element===element||c.element==='neutral')&&d.filter(x=>x===id).length<=Math.min(p.owned[id]||0,maxCopies(c))})}
export function normalize(raw){if(!raw||raw.version!==1)return freshProfile();const p=freshProfile();p.name=String(raw.name||'Viajero').trim().slice(0,20)||'Viajero';for(const k of ['trophies','coins','gems','wins','battles'])p[k]=int(raw[k],k==='trophies'?10000:999999);p.unlocked=['fire',...['water','wind','light','dark'].filter(x=>raw.unlocked?.includes(x))];p.owned={};for(const [id,n] of Object.entries(raw.owned||{}))if(CARD_BY_ID[id])p.owned[id]=int(n,maxCopies(CARD_BY_ID[id]));for(const e of p.unlocked){for(const c of CATALOG[e])p.owned[c.id]=maxCopies(c);const counts={};p.decks[e]=(Array.isArray(raw.decks?.[e])?raw.decks[e]:deckList(e).map(c=>c.id)).filter(id=>{const c=CARD_BY_ID[id];return c&&(c.element===e||c.element==='neutral')&&(counts[id]=(counts[id]||0)+1)<=Math.min(p.owned[id]||0,maxCopies(c))}).slice(0,15)}p.selected=p.unlocked.includes(raw.selected)?raw.selected:'fire';p.claimed=MILESTONES.filter(x=>raw.claimed?.includes(x.at)).map(x=>x.at);p.purchases=OFFERS.filter(x=>raw.purchases?.includes(x.id)).map(x=>x.id);p.beaten=BOSSES.filter(x=>raw.beaten?.includes(x.at)).map(x=>x.at);p.settled=Array.isArray(raw.settled)?raw.settled.filter(x=>typeof x==='string').slice(-100):[];p.playerId=/^CD-[A-Z0-9]{6,12}$/.test(raw.playerId)?raw.playerId:p.playerId;p.friends=Array.isArray(raw.friends)?raw.friends.filter(f=>/^CD-[A-Z0-9]{6,12}$/.test(f.id)).slice(0,50).map(f=>({id:f.id,name:String(f.name||f.id).slice(0,20)})):[];p.tutorial=!!raw.tutorial;p.sort=raw.sort==='alpha'?'alpha':'type';return p}
export function loadProfile(storage){try{return normalize(JSON.parse(storage.getItem(SAVE_KEY)))}catch{return freshProfile()}}
export function saveProfile(p,storage){try{storage.setItem(SAVE_KEY,JSON.stringify(p));return true}catch{return false}}
export function nextBoss(p){return BOSSES.find(x=>!p.beaten.includes(x.at))}
export function giveCards(p,ids){let converted=0;for(const id of ids){const c=CARD_BY_ID[id];if(!c)continue;const old=p.owned[id]||0,cap=maxCopies(c);p.owned[id]=Math.min(cap,old+1);if(old>=cap){p.coins+=20;converted+=20}}return converted}
export function claim(p,at){const m=MILESTONES.find(x=>x.at===at);if(!m||p.trophies<at||p.claimed.includes(at))return false;p.claimed.push(at);p.coins+=m.coins;p.gems+=m.gems;const converted=giveCards(p,Array(m.count).fill(m.card));return {...m,converted}}
export function purchase(p,id){const o=OFFERS.find(x=>x.id===id);if(!o||p.purchases.includes(id)||p[o.currency]<o.cost)return false;p[o.currency]-=o.cost;p.purchases.push(id);return {...o,converted:giveCards(p,o.cards.flatMap(id=>[id,id]))}}
export function changeDeck(p,id,delta){const c=CARD_BY_ID[id],d=p.decks[p.selected];if(!c||!d||![-1,1].includes(delta)||!p.unlocked.includes(p.selected)||!['neutral',p.selected].includes(c.element))return false;const count=d.filter(x=>x===id).length;if(delta<0){const i=d.indexOf(id);if(i<0)return false;d.splice(i,1)}else{if(d.length>=15||count>=Math.min(p.owned[id]||0,maxCopies(c)))return false;d.push(id)}return true}
export function settle(p,id,result,encounter){if(p.settled.includes(id))return false;p.settled.push(id);p.settled=p.settled.slice(-100);if(encounter.practice)return {trophies:0,coins:0,gems:0,practice:true};p.battles++;const win=result===true;if(win)p.wins++;let gain=win?30:15,coins=win?70:25,gems=win?3:0,unlocked=null;const boss=nextBoss(p);if(encounter.boss){gain=0;if(win&&boss&&boss.at===encounter.boss&&p.trophies>=boss.at){p.beaten.push(boss.at);coins=200;gems=25;if(boss.unlock){unlock(p,boss.unlock);unlocked=boss.unlock}}}const before=p.trophies,limit=nextBoss(p)?.at??10000;p.trophies=Math.min(limit,10000,p.trophies+gain);p.coins+=coins;p.gems+=gems;if(encounter.tutorial)p.tutorial=true;return {trophies:p.trophies-before,coins,gems,unlocked,win}}
export function opponent(p,{practice=false,tutorial=false,random=Math.random}={}){const gate=nextBoss(p),boss=!practice&&!tutorial&&gate&&p.trophies>=gate.at?gate:null;const stage=p.beaten.filter(x=>x<=1200).length,level=Math.min(4,1+Math.floor(p.trophies/300));const keys=Object.keys(MAGES),element=boss?.element||keys[Math.floor(random()*keys.length)];let deck;if(boss){deck=deckList(element);if(boss.at>=2500)deck=deck.map((c,i)=>i%4===0?clone(CATALOG[keys[(keys.indexOf(element)+1)%5]].find(x=>x.cost===c.cost&&x.type===c.type)||c):c)}else{const max=tutorial?2:Math.min(10,4+stage+Math.floor(p.trophies/2500)),curve=[1,1,2,2,3,3,3,4,4,4,5,5,6,7,8];deck=curve.map((cost,i)=>{cost=Math.min(max,cost);const e=keys[Math.floor(random()*keys.length)],pool=CATALOG[e].filter(c=>c.cost===cost&&(i!==6&&i!==9?c.type==='minion':true));return clone(pool[Math.floor(random()*pool.length)]||CATALOG[e][0])})}const names=['Kael, mago errante','Lira, guardiana de ruinas','Orin, aprendiz del norte','Sira, exploradora arcana','Darion, custodio del puente'];return {id:`${Date.now()}-${Math.floor(random()*1e12)}`,element,name:tutorial?'Constructos del santuario':boss?boss.name:names[Math.floor(random()*names.length)],boss:boss?.at||null,level:boss?4:level,deck,practice,tutorial,label:tutorial?'Tutorial':boss?'Jefe':level===1?'Iniciado':level===2?'Adepto':level===3?'Veterano':'Maestro'}}
