import {MAGES,CATALOG,deckList} from './cards.js';
const copy=o=>JSON.parse(JSON.stringify(o));
export const targetKey=t=>`${t.side}-${t.kind}-${t.lane}-${t.slot||0}`;
export class Duel{
 constructor(random=Math.random){this.random=random;this.uid=0;this.sides=[];this.events=[];this.log=[];this.over=false;this.active=0;this.round=1}
 emit(type,data={}){this.events.push({type,...data})}
 note(text){this.log.unshift(text);this.log=this.log.slice(0,60)}
 drainEvents(){return this.events.splice(0)}
 shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(this.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
 side(element,heavy){return {element,hand:[],deck:this.shuffle(deckList(element,heavy)),grave:[],lanes:Array.from({length:3},()=>[null,null]),runes:[null,null,null],crystals:[15,30,15].map(hp=>({hp,max:hp,shield:0})),mana:0,maxMana:0,turns:0,powerUsed:false,awake:false,lightUsed:false,fireUsed:false,fatigue:0}}
 start(element,heavy){this.uid=0;this.events=[];this.log=[];this.over=false;this.winner=null;this.active=0;this.round=1;const other=Object.keys(MAGES).filter(e=>e!==element);const foe=other[Math.floor(this.random()*other.length)];this.sides=[this.side(element,heavy),this.side(foe,MAGES[foe].heavy)];for(let p=0;p<2;p++){this.draw(p,4);const s=this.sides[p];if(!s.hand.some(c=>c.type==='minion'&&c.cost===1)){const i=s.deck.findIndex(c=>c.type==='minion'&&c.cost===1);if(i>=0)[s.hand[0],s.deck[i]]=[s.deck[i],s.hand[0]]}}this.begin(0);this.note(`Duelo en el Santuario del Umbral: ${MAGES[element].name} contra ${MAGES[foe].name}.`);this.emit('start',{element})}
 units(p){return this.sides[p].lanes.flatMap((lane,laneIndex)=>lane.flatMap((u,slot)=>u?[{u,side:p,lane:laneIndex,slot,kind:'unit'}]:[]))}
 empty(p){const a=[];this.sides[p].lanes.forEach((lane,l)=>lane.forEach((u,slot)=>{if(!u)a.push({side:p,kind:'unit',lane:l,slot})}));return a}
 stats(p,l,u){let atk=u.atk+(u.focus||0),max=u.hp;const aura=this.sides[p].runes[l]?.effect;const mods={vigor:[2,2],fragile:[-1,-2],bulwark:[0,4],rage:[3,0],weak:[-2,0],radiance:[1,2]};if(mods[aura]){atk+=mods[aura][0];max+=mods[aura][1]}if(u.weak?.left>0)atk-=u.weak.amount;if(this.sides[p].element==='dark'&&this.sides[p].awake)atk+=2;max=Math.max(1,max);return {atk:Math.max(0,atk),max,hp:Math.max(0,max-u.damage)}}
 has(p,l,u,k){const rune=this.sides[p].runes[l];return u.kw.includes(k)||rune?.effect===k||k==='rush'&&rune?.effect==='radiance'&&rune.element==='wind'}
 ready(p,l,u){return !!u&&!u.attacked&&!u.freeze&&(u.born!==this.sides[p].turns||this.has(p,l,u,'rush'))}
 accessible(p,l){const s=this.sides[p];return s.crystals[l].hp>0&&(l!==1||s.crystals[0].hp===0||s.crystals[2].hp===0)}
 tidy(p){for(const t of this.units(p))if(this.stats(p,t.lane,t.u).hp<=0){this.sides[p].grave.push(copy(t.u.printed));this.sides[p].lanes[t.lane][t.slot]=null;this.emit('death',{target:t,element:t.u.element,name:t.u.name});this.note(`${t.u.name} abandona el campo.`)}}
 crystalDamage(p,l,n,awaken=true){if(this.over)return 0;const s=this.sides[p],c=s.crystals[l];if(c.hp===0)return 0;let left=Math.max(0,n);const blocked=Math.min(c.shield,left);c.shield-=blocked;left-=blocked;const actual=Math.min(c.hp,left);c.hp-=actual;this.emit('damage',{target:{side:p,kind:'crystal',lane:l,slot:0},amount:actual,blocked});if(c.hp===0){s.runes[l]=null;this.tidy(p);this.emit('shatter',{target:{side:p,kind:'crystal',lane:l,slot:0}});this.note(`Un cristal de ${MAGES[s.element].name} se ha quebrado.`);if(l===1){this.over=true;this.winner=1-p;this.emit('over',{winner:1-p})}}else if(l===1&&actual>0&&awaken&&!s.awake)this.awaken(p);return actual}
 damage(t,n){const s=this.sides[t.side];if(t.kind==='crystal')return this.crystalDamage(t.side,t.lane,n);const u=s.lanes[t.lane][t.slot];if(!u)return 0;let left=Math.max(0,n),block=Math.min(left,u.shield);u.shield-=block;left-=block;const amount=Math.min(this.stats(t.side,t.lane,u).hp,left);u.damage+=left;this.emit('damage',{target:t,amount,blocked:block});return amount}
 heal(t,n){const s=this.sides[t.side];let amount=0;if(t.kind==='crystal'){const c=s.crystals[t.lane];if(c.hp>0){amount=Math.min(n,c.max-c.hp);c.hp+=amount}}else{const u=s.lanes[t.lane][t.slot];if(u){amount=Math.min(n,u.damage);u.damage-=amount}}if(amount)this.emit('heal',{target:t,amount});return amount}
 shield(t,n){const s=this.sides[t.side],u=t.kind==='crystal'?s.crystals[t.lane]:s.lanes[t.lane][t.slot];if(!u||t.kind==='crystal'&&u.hp===0)return;const amount=n+(s.element==='wind'&&s.awake?1:0);u.shield+=amount;this.emit('shield',{target:t,amount})}
 core(p){return {side:p,kind:'crystal',lane:1,slot:0}}
 awaken(p){const s=this.sides[p];s.awake=true;this.emit('awaken',{side:p,element:s.element});this.note(`${MAGES[s.element].name} despierta.`);if(s.element==='water'){this.heal(this.core(p),6);this.revive(p,5)}if(s.element==='wind')s.crystals[1].shield+=8}
 draw(p,n=1){const s=this.sides[p];for(let i=0;i<n&&!this.over;i++){if(s.deck.length){const c=s.deck.shift();if(s.hand.length<10){s.hand.push(c);this.emit('draw',{side:p})}else this.note(`${MAGES[s.element].name} tiene la mano llena.`)}else{this.crystalDamage(p,1,++s.fatigue);this.note(`Fatiga ${s.fatigue}.`)}}}
 summon(p,card,t,entries=true){const s=this.sides[p];if(!t||s.lanes[t.lane][t.slot])return false;const u={...copy(card),printed:copy(card),uid:++this.uid,kw:[...(card.kw||[])],damage:0,shield:0,focus:0,burn:null,weak:null,freeze:0,attacked:false,moved:false,born:s.turns};s.lanes[t.lane][t.slot]=u;this.emit('summon',{target:t,card:copy(card),element:card.element});this.note(`${MAGES[s.element].name} invoca ${card.name}.`);if(entries){this.entry(p,t,u);if(s.awake&&s.element==='light'&&!s.lightUsed){s.lightUsed=true;this.echo(p,t.lane,u,1)}}return u}
 echo(p,l,source,n=1){const spot=this.empty(p).find(t=>t.lane===l)||this.empty(p)[0];if(!spot)return false;return this.summon(p,{...copy(source.printed||source),name:`Eco de ${source.name}`,atk:n,hp:n,kw:[],entry:null,cost:0,kind:'minion',legend:false},spot,false)}
 revive(p,max=99,spot){const s=this.sides[p];spot=spot||this.empty(p)[0];if(!spot||s.lanes[spot.lane][spot.slot])return false;for(let i=s.grave.length-1;i>=0;i--)if(s.grave[i].cost<=max){const c=s.grave.splice(i,1)[0];return this.summon(p,c,spot,false)}return false}
 entry(p,t,u){const s=this.sides[p],n=u.entryPower||0;switch(u.entry){case 'healCore':this.heal(this.core(p),n);break;case 'selfShield':this.shield(t,n);break;case 'echo':this.echo(p,t.lane,u,1);break;case 'allShield':for(const x of this.units(p))this.shield(x,n);break;case 'allBuff':for(const x of this.units(p))if(x.u!==u){x.u.atk+=n;x.u.hp+=n}break;case 'allDamage':for(const x of this.units(1-p))this.damage(x,n);this.tidy(1-p);break;case 'revive':this.revive(p,5);break;case 'laneBurn':for(const x of this.units(1-p).filter(x=>x.lane===t.lane))x.u.burn={amount:2,left:3,source:p};break;case 'laneWeaken':for(const x of this.units(1-p).filter(x=>x.lane===t.lane))x.u.weak={amount:n,left:2};break}}
 begin(p){if(this.over)return;this.active=p;const s=this.sides[p];s.turns++;s.maxMana=Math.min(10,s.maxMana+1);s.mana=s.maxMana;s.powerUsed=false;s.lightUsed=false;s.fireUsed=false;for(const t of this.units(p)){t.u.attacked=false;t.u.moved=false;t.u.focus=0}this.draw(p);if(p===1&&s.turns===1){s.mana++;this.note('El rival recibe una Esquirla de Maná para su primer turno.')}this.emit('turn',{side:p,round:this.round})}
 end(){if(this.over)return false;const p=this.active,s=this.sides[p];for(const t of this.units(p)){const u=t.u;if(u.burn?.left>0){const source=this.sides[u.burn.source];this.damage(t,u.burn.amount+(source.element==='fire'&&source.awake?1:0));u.burn.left--}if(s.runes[t.lane]?.effect==='scorch')this.damage(t,2);if(u.weak?.left>0)u.weak.left--;if(u.freeze)u.freeze--;u.focus=0}this.tidy(p);if(s.element==='dark'&&s.awake)this.crystalDamage(p,1,2,false);if(this.over)return true;if(p===1)this.round++;this.begin(1-p);return true}
 targets(p,card){const type=card.target,s=this.sides[p],a=[];if(card.type==='minion')return this.empty(p);if(card.type==='rune'){const side=card.polarity==='bad'?1-p:p;return this.sides[side].crystals.flatMap((c,lane)=>c.hp>0?[{side,kind:'rune',lane,slot:0}]:[])}if(type==='none')return a;for(let side=0;side<2;side++)for(let lane=0;lane<3;lane++){
  const team=this.sides[side];for(let slot=0;slot<2;slot++){const u=team.lanes[lane][slot],t={side,kind:'unit',lane,slot};if(type==='enemyUnit'&&side!==p&&u)a.push(t);if(['ownUnit','ownUnitCrystal','ownUnitSpace'].includes(type)&&side===p&&u&&(type!=='ownUnitSpace'||this.empty(p).length))a.push(t);if(type==='ownDamaged'&&side===p&&u&&u.damage>0)a.push(t);if(type==='ownEmpty'&&side===p&&!u&&s.grave.length)a.push(t)}
  if(side===p&&['ownUnitCrystal','ownDamaged'].includes(type)&&team.crystals[lane].hp>0&&(type!=='ownDamaged'||team.crystals[lane].hp<team.crystals[lane].max))a.push({side,kind:'crystal',lane,slot:0});
  if((type==='enemyLane'&&side!==p||type==='ownLane'&&side===p)&&team.lanes[lane].some(Boolean))a.push({side,kind:'rune',lane,slot:0});
 }return a}
 canPlay(p,c){if(!c||this.over||this.active!==p||this.sides[p].mana<c.cost)return false;if(c.target==='none'){if(['buffAll','allBuffShield','allShieldDraw'].includes(c.fx))return this.units(p).length>0;if(c.fx==='allDamage')return this.units(1-p).length>0;return true}return this.targets(p,c).length>0}
 play(p,index,target){const s=this.sides[p],card=s.hand[index];if(!this.canPlay(p,card))return false;if(card.target!=='none'&&!this.targets(p,card).some(t=>target&&targetKey(t)===targetKey(target)))return false;s.mana-=card.cost;s.hand.splice(index,1);if(card.type==='minion')this.summon(p,card,target);else if(card.type==='rune'){this.sides[target.side].runes[target.lane]=copy(card);this.tidy(target.side);this.emit('rune',{target,element:card.element,curse:card.polarity==='bad'});this.note(`${card.name} transforma el cristal.`)}else{this.emit('spell',{side:p,target,element:card.element,name:card.name});this.effect(p,card,target);this.note(`${MAGES[s.element].name} lanza ${card.name}.`)}return true}
 effect(p,c,t){const s=this.sides[p],u=t?.kind==='unit'?this.sides[t.side].lanes[t.lane][t.slot]:null,n=c.power||0,bonus=s.element==='dark'&&s.awake?1:0;let amount=0;const laneUnits=side=>this.units(side).filter(x=>x.lane===t.lane);switch(c.fx){
 case 'spark':this.damage(t,u.burn?.left>0?2:1);break;
 case 'damage':this.damage(t,n+bonus+(u.burn?.left>0?(c.bonusBurn||0):0));break;
 case 'damageDraw':this.damage(t,n+bonus);this.draw(p);break;
 case 'damageFreeze':this.damage(t,n+bonus);u.freeze=1;break;
 case 'damageShield':this.damage(t,n+bonus);this.shield(this.core(p),4);break;
 case 'burn':u.burn={amount:n,left:3,source:p};break;
 case 'weaken':u.weak={amount:n,left:2};break;
 case 'focus':u.focus+=n;break;
 case 'heal':this.heal(t,n);break;
 case 'shield':this.shield(t,n);break;
 case 'buff':u.atk+=n;u.hp+=n;break;
 case 'draw':this.draw(p,n);break;
 case 'buffAll':for(const x of this.units(p)){x.u.atk+=n;x.u.hp+=n}break;
 case 'clone':this.echo(p,t.lane,u,2);break;
 case 'revive':this.revive(p,99,t);break;
 case 'reviveBuff':{const revived=this.revive(p,99,t);if(revived){revived.atk+=n;revived.hp+=n}break}
 case 'laneDamage':case 'laneDrain':case 'laneFreeze':for(const x of laneUnits(1-p)){amount+=this.damage(x,n+bonus);if(c.fx==='laneFreeze')x.u.freeze=1}if(c.fx==='laneDrain')this.heal(this.core(p),amount);break;
 case 'laneWeaken':for(const x of laneUnits(1-p))x.u.weak={amount:n,left:2};break;
 case 'laneHeal':for(const x of laneUnits(p))this.heal(x,n);this.heal({side:p,kind:'crystal',lane:t.lane},n);break;
 case 'laneShield':for(const x of laneUnits(p))this.shield(x,n);this.shield({side:p,kind:'crystal',lane:t.lane},n);break;
 case 'laneBuff':for(const x of laneUnits(p)){x.u.atk+=n;x.u.hp+=n}this.heal({side:p,kind:'crystal',lane:t.lane},3);break;
 case 'allDamage':for(const x of this.units(1-p))this.damage(x,n+bonus);break;
 case 'allHealDraw':for(const x of this.units(p))this.heal(x,n);for(let l=0;l<3;l++)this.heal({side:p,kind:'crystal',lane:l},n);this.draw(p,2);break;
 case 'allShieldDraw':for(const x of this.units(p))this.shield(x,n);this.draw(p,2);break;
 case 'allBuffShield':for(const x of this.units(p)){x.u.atk+=n;x.u.hp+=n;this.shield(x,3)}break;
 case 'drain':amount=this.damage(t,n+bonus);this.heal(this.core(p),amount);break;
 default:throw new Error(`Efecto desconocido: ${c.fx}`)
 }this.tidy(0);this.tidy(1)}
 powerTargets(p){return this.targets(p,{type:'spell',...MAGES[this.sides[p].element].power})}
 usePower(p,target){const s=this.sides[p];if(this.over||p!==this.active||s.mana<1||s.powerUsed||!this.powerTargets(p).some(t=>target&&targetKey(t)===targetKey(target)))return false;s.mana--;s.powerUsed=true;const power=MAGES[s.element].power;this.emit('power',{side:p,target,element:s.element});this.effect(p,power,target);this.note(`${MAGES[s.element].name}: ${power.name}.`);return true}
 attackTargets(p,l,slot){const u=this.sides[p].lanes[l][slot];if(!this.ready(p,l,u)||this.over||this.active!==p)return [];const s=this.sides[1-p],a=this.units(1-p).filter(t=>t.lane===l).map(({side,kind,lane,slot})=>({side,kind,lane,slot}));if(this.accessible(1-p,l)&&!s.lanes[l].some(v=>v&&this.has(1-p,l,v,'guard'))&&u.born!==this.sides[p].turns)a.push({side:1-p,kind:'crystal',lane:l,slot:0});return a}
 strike(p,l,slot,t){if(!this.attackTargets(p,l,slot).some(x=>targetKey(x)===targetKey(t)))return false;const s=this.sides[p],u=s.lanes[l][slot],source={side:p,kind:'unit',lane:l,slot};let atk=this.stats(p,l,u).atk;u.attacked=true;this.emit('attack',{source,target:t,element:u.element});if(t.kind==='crystal'){if(s.element==='fire'&&s.awake&&!s.fireUsed){atk+=2;s.fireUsed=true}const damage=this.damage(t,atk);if(this.has(p,l,u,'lifesteal'))this.heal(this.core(p),damage)}else{const def=this.sides[1-p].lanes[l][t.slot],before=this.stats(1-p,l,def).hp+def.shield,counter=this.stats(1-p,l,def).atk,leech=this.has(p,l,u,'lifesteal'),overflow=this.has(p,l,u,'overflow'),counterLeech=this.has(1-p,l,def,'lifesteal');const dealt=this.damage(t,atk),returned=this.damage(source,counter);if(leech)this.heal(this.core(p),dealt);if(counterLeech)this.heal(this.core(1-p),returned);if(u.kw.includes('burnHit'))def.burn={amount:1,left:3,source:p};this.tidy(0);this.tidy(1);if(overflow&&atk>before&&this.accessible(1-p,l)){const d=this.crystalDamage(1-p,l,atk-before);if(leech)this.heal(this.core(p),d);this.emit('overflow',{target:{side:1-p,kind:'crystal',lane:l,slot:0},amount:d})}}this.note(`${u.name} ataca en el carril ${l+1}.`);return true}
 moves(p,l,slot){const u=this.sides[p].lanes[l][slot];if(this.over||this.active!==p||!u||u.moved||this.sides[p].mana<1)return [];return this.empty(p).filter(t=>t.lane!==l)}
 move(p,l,slot,t){if(!this.moves(p,l,slot).some(x=>targetKey(x)===targetKey(t)))return false;const s=this.sides[p],u=s.lanes[l][slot];s.mana--;s.lanes[l][slot]=null;s.lanes[t.lane][t.slot]=u;u.moved=true;this.tidy(p);this.emit('move',{source:{side:p,kind:'unit',lane:l,slot},target:t,element:u.element});return true}
 aiChoice(){const p=this.active,s=this.sides[p];if(p!==1||this.over)return null;const unitScore=t=>{const u=this.sides[t.side].lanes[t.lane][t.slot];return u?this.stats(t.side,t.lane,u).atk+this.stats(t.side,t.lane,u).hp:0};
  const scoreTarget=(c,t)=>{if(c.type==='minion'){const open=this.accessible(0,1);return (t.lane===1?(open?12:1):this.sides[0].crystals[t.lane].hp>0?7:0)+this.sides[0].lanes[t.lane].filter(Boolean).length-s.lanes[t.lane].filter(Boolean).length}if(c.type==='rune'){const side=c.polarity==='bad'?0:1;return this.sides[side].lanes[t.lane].filter(Boolean).length*4+(this.sides[side].runes[t.lane]?0:4)}if(['heal','laneHeal'].includes(c.fx)){if(t.kind==='crystal')return s.crystals[t.lane].max-s.crystals[t.lane].hp;return s.lanes[t.lane][t.slot]?.damage||0}if(c.target==='enemyUnit')return unitScore(t);return unitScore(t)+(t.lane===1?1:0)};
  const choices=s.hand.flatMap((c,index)=>{if(!this.canPlay(p,c))return [];const ts=this.targets(p,c).sort((a,b)=>scoreTarget(c,b)-scoreTarget(c,a));return [{type:'card',index,target:ts[0],score:c.cost+(c.type==='minion'?2:0)+(c.type==='rune'&&!this.units(c.polarity==='bad'?0:1).length?-4:0)}]}).sort((a,b)=>b.score-a.score);if(choices.length)return choices[0];
  if(!s.powerUsed&&s.mana>=1){const ts=this.powerTargets(p).sort((a,b)=>scoreTarget(MAGES[s.element].power,b)-scoreTarget(MAGES[s.element].power,a));if(ts.length)return {type:'power',target:ts[0]}}
  for(const x of this.units(p)){const ts=this.attackTargets(p,x.lane,x.slot);if(ts.length){const lethal=ts.find(t=>t.kind==='crystal'&&this.sides[0].crystals[t.lane].hp<=this.stats(p,x.lane,x.u).atk);const trade=ts.find(t=>t.kind==='unit'&&this.stats(0,t.lane,this.sides[0].lanes[t.lane][t.slot]).hp<=this.stats(p,x.lane,x.u).atk);return {type:'attack',...x,target:lethal||trade||ts.find(t=>t.kind==='crystal')||ts[0]}}}
  for(const x of this.units(p)){if(!this.ready(p,x.lane,x.u))continue;const move=this.moves(p,x.lane,x.slot).find(t=>this.sides[0].lanes[t.lane].some(Boolean)||this.accessible(0,t.lane));if(move&&this.sides[0].crystals[x.lane].hp===0)return {type:'move',...x,target:move}}
  return null}
 act(choice){switch(choice.type){case 'card':return this.play(this.active,choice.index,choice.target);case 'power':return this.usePower(this.active,choice.target);case 'attack':return this.strike(this.active,choice.lane,choice.slot,choice.target);case 'move':return this.move(this.active,choice.lane,choice.slot,choice.target)}return false}
}
