import {MAGES,CATALOG,KEYWORDS,RULES,VERSION,deckList,curve} from './cards.js';
import {Duel,targetKey} from './engine.js';
import {icon,portrait,figure,prism,runestone,runeColors,cardMarkup,kindNames} from './art.js';
import {Sound} from './audio.js';
const $=id=>document.getElementById(id),duel=new Duel(),sound=new Sound();
let chosen='fire',selection=null,busy=false,match=0,toastTimer,announceTimer,installPrompt=null,collectionMode=false;
const heavy=Object.fromEntries(Object.entries(MAGES).map(([k,m])=>[k,m.heavy]));
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fromKey=key=>{const [side,kind,lane,slot]=key.split('-');return {side:+side,kind,lane:+lane,slot:+slot}};
const clone=o=>JSON.parse(JSON.stringify(o));
function updateSound(){document.querySelectorAll('.sound-toggle').forEach(b=>{b.innerHTML=icon(sound.enabled?'sound':'mute');b.setAttribute('aria-label',sound.enabled?'Desactivar sonido':'Activar sonido');b.setAttribute('aria-pressed',String(sound.enabled))})}
document.addEventListener('pointerdown',()=>sound.unlock(),{passive:true});
document.querySelectorAll('.sound-toggle').forEach(b=>b.onclick=async()=>{await sound.unlock();sound.toggle();updateSound();if(sound.enabled)sound.play('rune',chosen)});
function toast(text){$('toast').textContent=text;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),2600)}
function announce(title,sub=''){clearTimeout(announceTimer);const el=$('announcement');el.innerHTML=`${escape(title)}${sub?`<small>${escape(sub)}</small>`:''}`;el.classList.remove('hidden');el.style.animation='none';void el.offsetWidth;el.style.animation='';announceTimer=setTimeout(()=>el.classList.add('hidden'),reduced?1000:1200)}
function openModal(html){$('modal').innerHTML=`<button class="round-button modal-close" id="closeModal" aria-label="Cerrar">${icon('close')}</button>${html}`;$('overlay').classList.remove('hidden');$('closeModal').onclick=closeModal;$('closeModal').focus({preventScroll:true})}
function closeModal(){$('overlay').classList.add('hidden')}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();selection=null;if(duel.sides.length)render()}});
$('overlay').addEventListener('click',e=>{if(e.target===$('overlay'))closeModal()});
function renderMenu(){const m=MAGES[chosen];$('app').style.setProperty('--element',m.color);$('brandSeal').innerHTML=icon('rune');$('mageStage').innerHTML=`${portrait(chosen)}<div class="stage-title"><span class="element-tag">${icon(chosen)} ${m.element}</span><h2>${m.name}</h2><p>${m.title}</p></div>`;$('mageChoices').innerHTML=Object.entries(MAGES).map(([key,v])=>`<button class="mage-choice ${key===chosen?'selected':''}" data-mage="${key}" style="--element:${v.color}" aria-label="Elegir ${v.name}, ${v.element}" aria-pressed="${key===chosen}">${portrait(key)}<span class="mage-mini-name">${v.name}</span></button>`).join('');$('mageDescription').textContent=m.desc;$('menuPower').innerHTML=`<span class="power-glyph">${icon(chosen)}</span><div><b>${m.power.name} · Poder de mago</b><p>${m.power.text}</p></div><span class="power-cost">1 ${icon('mana')}</span>`;updateSound()}
$('mageChoices').onclick=e=>{const b=e.target.closest('[data-mage]');if(!b)return;chosen=b.dataset.mage;sound.play('select',chosen);renderMenu()};
function showRules(){openModal(`<h2>El arte del duelo</h2><p>Rompe un cristal lateral y después el núcleo para ganar.</p><ul class="rule-list"><li><strong>Tu mano está siempre abajo.</strong> Desliza para ver todas las cartas. Toca una y elige una casilla iluminada. La lupa muestra todos sus detalles.</li><li><strong>Dos esbirros, lado a lado.</strong> Cada cristal sostiene un carril con dos esbirros y una runa. Las buenas se colocan en tus cristales; las maldiciones, en los del rival. Una runa nueva reemplaza la anterior y cambia el color del cristal.</li><li><strong>Atacar:</strong> toca un esbirro tuyo y luego un enemigo iluminado de su carril. Los esbirros se hacen daño simultáneamente. Guardia protege el cristal. Ímpetu permite atacar esbirros al entrar, pero no cristales.</li><li><strong>Mover:</strong> toca un aliado y el botón de flechas. Cambiar de carril cuesta 1 maná, una vez por esbirro y turno.</li><li><strong>Poder de mago:</strong> cuesta 1 maná, una vez por turno. Elige un objetivo después de tocarlo.</li><li><strong>Ritmo:</strong> empiezas con 4 cartas, incluyendo un aprendiz, y robas una al comenzar cada turno. El maná aumenta de 1 a 10. Tus mazos tienen solo dos cartas de coste 8 o más.</li><li><strong>Estados:</strong> Quemadura daña al final de los próximos 3 turnos del dueño. Congelado impide atacar durante 1 turno. Barrera absorbe daño antes que la vida.</li><li><strong>Despertar:</strong> el primer daño no letal a tu núcleo activa la habilidad de tu mago. Un cristal destruido pierde su runa.</li></ul>${typeLegend()}<button id="rulesDone" class="primary">Entendido</button>`);$('rulesDone').onclick=closeModal}
function typeLegend(){return `<div class="type-legend"><span style="--card-a:#74404f">Esbirros · burdeo</span><span style="--card-a:#dad4bb;color:#233a3c">Monstruos · marfil</span><span style="--card-a:#b2709e">Runas · rosa</span><span style="--card-a:#456e89">Hechizos · azul</span></div>`}
$('menuHelp').onclick=showRules;
function showDeck(){const cards=collectionMode?CATALOG[chosen]:deckList(chosen,heavy[chosen]),counts=new Map();for(const c of cards)counts.set(c.id,(counts.get(c.id)||0)+1);const unique=[...new Map(cards.map(c=>[c.id,c])).values()].sort((a,b)=>a.cost-b.cost);openModal(`<h2>El legado de ${MAGES[chosen].name}</h2><p>30 cartas · 2 finales de coste alto · poder de 1 maná</p><div class="deck-curve" aria-label="Distribución de costes del mazo">${curve(chosen,heavy[chosen]).map((n,i)=>`<div class="curve-column" style="--count:${n}"><b>${n}</b><i></i><small>${i+1}</small></div>`).join('')}</div><div class="heavy-choices"><small>Tu penúltimo final:</small>${[8,9].map(n=>`<button data-heavy="${n}" class="${heavy[chosen]===n?'active':''}">${n} maná</button>`).join('')}</div><div class="deck-mode"><button id="showDeckCards" class="${!collectionMode?'active':''}">Mi mazo · 30</button><button id="showCollection" class="${collectionMode?'active':''}">Colección · 1 a 10</button></div>${typeLegend()}<div class="collection-grid">${unique.map(c=>`<button class="collection-card" data-card="${c.id}" aria-label="Ver ${c.name}, ${c.cost} maná">${cardMarkup(c,{count:collectionMode?0:counts.get(c.id)})}</button>`).join('')}</div>`);$('showDeckCards').onclick=()=>{collectionMode=false;showDeck()};$('showCollection').onclick=()=>{collectionMode=true;showDeck()};$('modal').querySelectorAll('[data-heavy]').forEach(b=>b.onclick=()=>{heavy[chosen]=+b.dataset.heavy;showDeck()});$('modal').querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>showCard(CATALOG[chosen].find(c=>c.id===b.dataset.card),{back:showDeck}))}
$('deckButton').onclick=()=>{collectionMode=false;showDeck()};
function showCard(c,{unit=null,target=null,back=null}={}){const kws=(c.kw||[]).map(k=>`<div><b>${KEYWORDS[k]}:</b> ${RULES[k]}</div>`).join('');let current='';if(unit&&target){const st=duel.stats(target.side,target.lane,unit);const statuses=[unit.shield?`Barrera ${unit.shield}`:'',unit.freeze?'Congelado: 1 turno':'',unit.burn?.left>0?`Quemadura ${unit.burn.amount}: ${unit.burn.left} turnos`:'',unit.weak?.left>0?`−${unit.weak.amount} ATQ: ${unit.weak.left} turnos`:'',unit.focus?`+${unit.focus} ATQ hasta fin de turno`:''];current=`<p>En el campo: <b>${st.atk} ATQ · ${st.hp}/${st.max} VIDA</b><br>${statuses.filter(Boolean).join(' · ')}</p>`}openModal(`${cardMarkup(c,{large:true})}${current}<div class="keyword-definitions">${kws}${c.type==='rune'?'<div>La runa afecta a los dos esbirros de su cristal, incluidos los que invoques después. Sus efectos terminan al reemplazarla o destruir su cristal.</div>':''}</div><button id="cardBack" class="secondary">${back?'Volver al mazo':'Volver al tablero'}</button>`);$('cardBack').onclick=back||closeModal}
function selectedTargets(){if(!selection||duel.over||busy||duel.active!==0)return [];const s=duel.sides[0];if(selection.type==='card'){const c=s.hand[selection.index];return duel.canPlay(0,c)?duel.targets(0,c):[]}if(selection.type==='unit')return duel.attackTargets(0,selection.lane,selection.slot);if(selection.type==='move')return duel.moves(0,selection.lane,selection.slot);if(selection.type==='power'&&!s.powerUsed&&s.mana>=1)return duel.powerTargets(0);return []}
function renderBoard(p,id,targets){const s=duel.sides[p],m=MAGES[s.element];$(id).innerHTML=s.lanes.map((lane,l)=>{const rune=s.runes[l],c=s.crystals[l],color=rune?runeColors[rune.effect]:m.color;const runeKey=targetKey({side:p,kind:'rune',lane:l}),crystalKey=targetKey({side:p,kind:'crystal',lane:l});const runeTarget=targets.has(runeKey),crystalTarget=targets.has(crystalKey)||runeTarget;return `<div class="lane" data-lane="${l}" style="--rune:${color};--element:${m.color}"><div class="unit-pair">${lane.map((u,slot)=>{const t={side:p,kind:'unit',lane:l,slot},key=targetKey(t),selected=selection&&['unit','move'].includes(selection.type)&&p===0&&selection.lane===l&&selection.slot===slot;if(!u)return `<button class="slot empty ${targets.has(key)?'target':''}" data-target="${key}" aria-label="Casilla ${slot+1}, carril ${l+1}, ${p?'rival':'propia'}, vacía"></button>`;const st=duel.stats(p,l,u),kw=['guard','rush','overflow','lifesteal','burnHit'].filter(k=>duel.has(p,l,u,k));return `<button class="slot kind-${u.kind} ${p===0&&duel.ready(p,l,u)&&duel.active===0?'ready':''} ${selected?'selected':''} ${targets.has(key)?'target':''} ${u.freeze?'frozen':''}" data-target="${key}" data-unit="${u.uid}" aria-label="${escape(u.name)}, ${st.atk} ataque, ${st.hp} vida, carril ${l+1}, ${p?'rival':'propio'}"><span class="unit-base"></span><span class="standing">${figure(u)}</span><span class="unit-numbers"><b>${st.atk}</b><b class="hp">${st.hp}</b></span><span class="unit-status">${u.freeze?icon('freeze'):''}${u.burn?.left>0?icon('fire'):''}${kw.slice(0,2).map(k=>icon(k==='guard'?'shield':k==='burnHit'?'fire':k)).join('')}</span>${u.shield?`<span class="shield-tag">${u.shield}</span>`:''}</button>`}).join('')}</div><button class="rune-button ${rune?'filled':'empty'} ${runeTarget?'target':''}" data-target="${runeKey}" aria-label="${rune?escape(rune.name):'Ranura de runa'}, carril ${l+1}, ${p?'rival':'propia'}">${rune?runestone(rune):icon('rune')}</button><button class="crystal-button ${l===1?'core':''} ${c.hp===0?'dead':''} ${rune?'enchanted':''} ${crystalTarget?'target':''}" data-target="${crystalKey}" aria-label="Cristal ${l===1?'central':l===0?'izquierdo':'derecho'} ${p?'rival':'propio'}, ${c.hp} de ${c.max} vida${rune?', '+escape(rune.name):''}">${prism(color)}<span class="crystal-label">${l===1?'NÚCLEO':l===0?'OESTE':'ESTE'}</span><span class="crystal-hp">${c.hp}<small> / ${c.max}</small></span>${c.shield?`<span class="crystal-shield">${icon('shield')}${c.shield}</span>`:''}</button></div>`}).join('')}
function render(){if(!duel.sides.length)return;const [s,e]=duel.sides,targets=new Set(selectedTargets().map(targetKey));$('app').style.setProperty('--element',MAGES[s.element].color);$('enemyPortrait').innerHTML=portrait(e.element);$('playerPortrait').innerHTML=portrait(s.element);$('enemyName').textContent=MAGES[e.element].name+(e.awake?' · Despierto':'');$('playerName').textContent=MAGES[s.element].name+(s.awake?' · Despierto':'');$('enemyInfo').textContent=`${MAGES[e.element].element} · Maná ${e.mana}/${e.maxMana} · Mazo ${e.deck.length}`;$('playerInfo').textContent=`${MAGES[s.element].element} · Mazo ${s.deck.length} · Caídos ${s.grave.length}`;$('roundLabel').innerHTML=`RONDA<strong>${duel.round}</strong>`;$('enemyHand').innerHTML=Array.from({length:e.hand.length},(_,i)=>`<span class="card-back" style="--tilt:${(i%5-2)*3}deg">◇</span>`).join('')+`<small>${e.hand.length} cartas</small>`;$('turnLabel').textContent=duel.over?'DUELO TERMINADO':duel.active===0?'TU TURNO':'TURNO DEL RIVAL';renderBoard(1,'enemyBoard',targets);renderBoard(0,'playerBoard',targets);
 const scroll=$('hand').scrollLeft;$('hand').innerHTML=s.hand.map((c,i)=>`<button class="hand-card ${duel.canPlay(0,c)&&!busy?'playable':''} ${c.cost>s.mana?'unaffordable':''} ${selection?.type==='card'&&selection.index===i?'selected':''}" data-hand="${i}" aria-label="${escape(c.name)}, ${c.cost} maná, ${kindNames[c.kind]}. ${escape(c.text)}">${cardMarkup(c)}</button>`).join('');$('hand').scrollLeft=scroll;
 const power=MAGES[s.element].power;$('powerButton').innerHTML=`${icon(s.element)}<span><b>${power.name}</b><small>${s.powerUsed?'Usado este turno':'Poder de mago'}</small></span><span class="mini-cost">1</span>`;$('powerButton').classList.toggle('selected',selection?.type==='power');$('powerButton').disabled=busy||duel.over||duel.active!==0||s.powerUsed||s.mana<1;$('powerButton').setAttribute('aria-label',`${power.name}, poder de 1 maná. ${power.text}${s.powerUsed?' Ya usado.':''}`);
 $('manaBar').innerHTML=`<div class="mana-pips">${Array.from({length:s.maxMana},(_,i)=>`<i class="mana-pip ${i>=s.mana?'spent':''}"></i>`).join('')}</div><span class="mana-count">${s.mana}<small> / ${s.maxMana}</small></span>`;$('endButton').disabled=busy||duel.over||duel.active!==0;$('endButton').innerHTML=duel.over?'Duelo terminado':duel.active===1?'Juega el rival…':'Terminar turno <span>›</span>';renderContext();updateSound()}
function renderContext(){const s=duel.sides[0],c=selection?.type==='card'?s.hand[selection.index]:null;let text=duel.over?'El duelo ha terminado.':duel.active===1?'El rival está preparando su siguiente movimiento…':busy?'La magia toma forma…':`Tu mano · ${s.hand.length} cartas. Toca una carta y su destino.`;let actions='';if(c){text=`<b>${escape(c.name)}</b> · ${escape(c.text)}`;if(c.cost>s.mana)text=`<b>Necesitas ${c.cost} maná (${s.mana} disponible).</b> ${escape(c.name)}`;actions+=`<button class="icon-button" data-context="details" aria-label="Ver carta completa">${icon('eye')}</button>`;if(c.target==='none')actions+=`<button class="small-action" data-context="cast" ${!duel.canPlay(0,c)||busy?'disabled':''}>Lanzar</button>`}else if(selection?.type==='unit'){const u=s.lanes[selection.lane][selection.slot];if(u){const st=duel.stats(0,selection.lane,u);text=`<b>${escape(u.name)}</b> · ${st.atk} ATQ / ${st.hp} VIDA. ${duel.ready(0,selection.lane,u)?'Toca un enemigo iluminado.':'Descansa este turno.'}`;if(duel.moves(0,selection.lane,selection.slot).length)actions+=`<button class="icon-button" data-context="move" aria-label="Mover por 1 maná">${icon('move')}</button>`;actions+=`<button class="icon-button" data-context="details" aria-label="Ver esbirro">${icon('eye')}</button>`}}else if(selection?.type==='move')text='Elige una casilla libre de otro carril. Mover cuesta 1 maná.';else if(selection?.type==='power')text=`<b>${MAGES[s.element].power.name}</b> · ${MAGES[s.element].power.text} Toca un objetivo.`;if(selection)actions+=`<button class="icon-button" data-context="cancel" aria-label="Cancelar selección">${icon('close')}</button>`;$('contextText').innerHTML=text;$('contextActions').innerHTML=actions}
function clickHand(i){if(duel.over||busy||duel.active!==0)return;selection=selection?.type==='card'&&selection.index===i?null:{type:'card',index:i};sound.play('select',duel.sides[0].element);render()}
$('hand').onclick=e=>{const b=e.target.closest('[data-hand]');if(b)clickHand(+b.dataset.hand)};
function findTargetElement(t){return document.querySelector(`[data-target="${targetKey(t)}"]`)}
function locationOf(t){let el=t?findTargetElement(t):$('playerPortrait');if(!el)return null;const r=el.getBoundingClientRect(),app=$('app').getBoundingClientRect();return {x:r.left+r.width/2-app.left,y:r.top+r.height/2-app.top}}
function particle(kind,pos,tint,extra={}){if(!pos||reduced)return;const el=document.createElement('div');el.className='fx-'+kind;el.style.left=pos.x+'px';el.style.top=pos.y+'px';el.style.setProperty('--tint',tint);for(const [k,v] of Object.entries(extra))if(k==='text')el.textContent=v;else el.style.setProperty(k,v);$('fx').append(el);setTimeout(()=>el.remove(),1100)}
function burst(pos,color,n=13){particle('ring',pos,color);for(let i=0;i<n;i++){const angle=Math.PI*2*i/n,dist=24+Math.random()*43;particle('particle',pos,color,{'--dx':Math.cos(angle)*dist+'px','--dy':Math.sin(angle)*dist+'px'})}}
function bolt(from,to,color){if(!from||!to)return;particle('bolt',from,color,{'--dx':to.x-from.x+'px','--dy':to.y-from.y+'px'})}
async function perform(fn){if(busy||duel.over||duel.active!==0)return;busy=true;const token=match;await sound.unlock();if(token!==match)return;if(!fn()){busy=false;toast('Ese movimiento no está disponible.');render();return}selection=null;const events=duel.drainEvents();render();await animate(events);if(token!==match)return;busy=false;if(duel.over)showResult();else render()}
async function animate(events){const soundKinds=new Set();for(const ev of events){const target=ev.target,pos=locationOf(target),color=MAGES[ev.element||duel.sides[target?.side||0].element]?.color||'#e8d8a5';
  if(['summon','rune','spell','power','attack','awaken','shatter','death','heal','shield'].includes(ev.type)&&!soundKinds.has(ev.type)){sound.play(ev.type,ev.element||duel.sides[target?.side||0].element,ev.card?.cost>=8);soundKinds.add(ev.type)}
  switch(ev.type){case 'summon':burst(pos,color,ev.card.cost>=8?22:13);{const el=findTargetElement(target)?.querySelector('.standing');if(el&&!reduced)el.animate([{opacity:0,transform:'translateY(22px) scale(.45)',filter:'brightness(2)'},{opacity:1,transform:'translateY(0) scale(1)',filter:'brightness(1)'}],{duration:420,easing:'cubic-bezier(.12,.8,.3,1.3)'})}break;
  case 'attack':{const source=locationOf(ev.source);bolt(source,pos,color);particle('slash',pos,color);const el=findTargetElement(ev.source);if(el&&source&&pos&&!reduced)el.animate([{transform:'translate(0,0)'},{transform:`translate(${(pos.x-source.x)*.25}px,${(pos.y-source.y)*.25}px) scale(1.12)`,offset:.35},{transform:'translate(0,0)'}],{duration:300,easing:'ease-out'});break}
  case 'spell':case 'power':bolt(locationOf(null),pos||locationOf(duel.core(1)),color);burst(pos||locationOf(duel.core(1)),color);break;
  case 'rune':burst(locationOf({...target,kind:'crystal'}),runeColors[duel.sides[target.side].runes[target.lane]?.effect]||color,20);break;
  case 'damage':if(ev.amount)particle('number',pos,'#ffe3cf',{text:'−'+ev.amount});else if(ev.blocked)particle('number',pos,'#b5eafb',{text:'Barrera'});break;
  case 'heal':particle('number',pos,'#b6efc3',{text:'+'+ev.amount});break;
  case 'shield':particle('number',pos,'#afe7f3',{text:'+'+ev.amount});break;
  case 'death':case 'shatter':burst(pos,color,18);break;
  case 'awaken':announce(`${MAGES[ev.element].name} despierta`,'EL PODER DEL NÚCLEO');burst(locationOf(duel.core(ev.side)),color,24);break;
  case 'turn':if(ev.side===0){sound.play('turn',duel.sides[0].element);announce('Tu turno',`RONDA ${ev.round}`)}break;
  case 'draw':if(!soundKinds.has('draw')&&ev.side===0){sound.play('draw',duel.sides[0].element);soundKinds.add('draw')}break;
  case 'overflow':particle('number',pos,'#ffd899',{text:'Desborde'});break;
  }
 }await delay(reduced?80:events.some(e=>e.type==='awaken')?780:events.some(e=>['spell','summon','rune','attack','power'].includes(e.type))?430:180)}
function clickTarget(t){if(busy||duel.over||duel.active!==0)return;const ts=selectedTargets();let valid=ts.find(x=>targetKey(x)===targetKey(t));if(!valid&&['card','power'].includes(selection?.type))valid=ts.find(x=>x.side===t.side&&x.lane===t.lane&&x.kind==='rune');if(valid){if(selection.type==='card'){const i=selection.index;return perform(()=>duel.play(0,i,valid))}if(selection.type==='unit'){const {lane,slot}=selection;return perform(()=>duel.strike(0,lane,slot,valid))}if(selection.type==='move'){const {lane,slot}=selection;return perform(()=>duel.move(0,lane,slot,valid))}if(selection.type==='power')return perform(()=>duel.usePower(0,valid))}
 if(selection&&selection.type!=='unit'){toast('Elige un objetivo iluminado, o cancela la selección.');return}const s=duel.sides[t.side],u=t.kind==='unit'?s.lanes[t.lane][t.slot]:null;if(u&&t.side===0){selection={type:'unit',lane:t.lane,slot:t.slot};sound.play('select',s.element);render()}else if(u)showCard(u.printed,{unit:u,target:t});else if(t.kind==='rune'&&s.runes[t.lane])showCard(s.runes[t.lane]);else if(t.kind==='crystal'){const c=s.crystals[t.lane];toast(`${t.lane===1?'Núcleo':'Cristal'}: ${c.hp}/${c.max} vida${s.runes[t.lane]?' · '+s.runes[t.lane].name:''}. ${t.lane===1&&!duel.accessible(t.side,1)?'Destruye primero un lateral.':''}`)}}
for(const id of ['playerBoard','enemyBoard'])$(id).onclick=e=>{const b=e.target.closest('[data-target]');if(b)clickTarget(fromKey(b.dataset.target))};
$('contextActions').onclick=e=>{const b=e.target.closest('[data-context]');if(!b)return;const action=b.dataset.context;if(action==='cancel'){selection=null;render()}else if(action==='move'){selection={...selection,type:'move'};render()}else if(action==='cast'&&selection?.type==='card'){const i=selection.index;perform(()=>duel.play(0,i))}else if(action==='details'){if(selection?.type==='card')showCard(duel.sides[0].hand[selection.index]);else if(selection?.type==='unit'){const t={side:0,kind:'unit',lane:selection.lane,slot:selection.slot},u=duel.sides[0].lanes[t.lane][t.slot];if(u)showCard(u.printed,{unit:u,target:t})}}};
$('powerButton').onclick=()=>{if(busy||duel.active!==0||duel.over)return;if(!duel.powerTargets(0).length){toast('No hay objetivos disponibles para tu poder.');return}selection=selection?.type==='power'?null:{type:'power'};sound.play('select',duel.sides[0].element);render()};
async function enemyTurn(token){let guard=0;while(duel.active===1&&!duel.over&&token===match&&guard++<40){if(!$('overlay').classList.contains('hidden')){await delay(250);guard--;continue}const action=duel.aiChoice();if(!action)break;duel.act(action);const events=duel.drainEvents();render();await animate(events);await delay(reduced?50:180)}if(token!==match)return;if(!duel.over)duel.end();const events=duel.drainEvents();render();await animate(events);if(token!==match)return;busy=false;if(duel.over)showResult();else render()}
$('endButton').onclick=async()=>{if(busy||duel.active!==0||duel.over)return;selection=null;busy=true;const token=match;duel.end();render();await animate(duel.drainEvents());if(duel.over){busy=false;showResult();return}await enemyTurn(token)};
async function start(){await sound.unlock();match++;busy=false;selection=null;closeModal();duel.start(chosen,heavy[chosen]);$('menu').classList.add('hidden');$('game').classList.remove('hidden');$('battlefield').scrollTop=0;render();sound.play('start',chosen);announce('Que comience el duelo',MAGES[chosen].title.toUpperCase());duel.drainEvents()}
$('startButton').onclick=start;
function showResult(){busy=false;render();const win=duel.winner===0;sound.play(win?'victory':'shatter',duel.sides[0].element);openModal(`<div class="victory-art">${prism(win?'#e9cf82':'#9eafbd')}</div><h2>${win?'El santuario es tuyo':'Tu núcleo se ha quebrado'}</h2><p>${win?'Tu magia ha abierto el camino.':'Cada duelo revela una nueva estrategia.'}<br>Ronda ${duel.round} · ${MAGES[duel.sides[0].element].name} contra ${MAGES[duel.sides[1].element].name}</p><div class="modal-actions"><button id="again" class="primary">Otra partida</button><button id="chooseAgain" class="secondary">Elegir mago</button></div>`);$('again').onclick=start;$('chooseAgain').onclick=toMenu}
function toMenu(){match++;busy=false;selection=null;closeModal();$('game').classList.add('hidden');$('menu').classList.remove('hidden');renderMenu()}
$('menuGame').onclick=()=>{openModal(`<h2>El santuario</h2><p>${MAGES[duel.sides[0].element].name} · Ronda ${duel.round}</p><div class="volume-row"><span>Volumen</span><input id="volume" aria-label="Volumen de efectos" type="range" min="0" max="0.7" step="0.05" value="${sound.volume}"></div><div class="modal-actions"><button id="resume" class="primary">Continuar</button><button id="rulesGame" class="secondary">Reglas</button></div><div class="modal-actions"><button id="viewLog" class="secondary">Ver registro</button><button id="leaveGame" class="secondary">Salir del duelo</button></div>`);$('volume').oninput=e=>sound.setVolume(+e.target.value);$('resume').onclick=closeModal;$('rulesGame').onclick=showRules;$('viewLog').onclick=()=>openModal(`<h2>Memoria del duelo</h2><div class="log-entries">${duel.log.map(x=>`<p>${escape(x)}</p>`).join('')}</div>`);$('leaveGame').onclick=()=>{openModal(`<h2>¿Abandonar el duelo?</h2><p>Esta partida terminará y volverás a elegir mago.</p><div class="modal-actions"><button id="keepPlaying" class="primary">Seguir jugando</button><button id="confirmLeave" class="secondary">Abandonar</button></div>`);$('keepPlaying').onclick=closeModal;$('confirmLeave').onclick=toMenu}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('installButton').classList.remove('hidden')});$('installButton').onclick=async()=>{if(!installPrompt)return;await installPrompt.prompt();installPrompt=null;$('installButton').classList.add('hidden')};window.addEventListener('appinstalled',()=>$('installButton').classList.add('hidden'));
// Register only at the published root; the /v03/ review build does not replace offline caches.
if('serviceWorker' in navigator&&!location.pathname.includes('/v03/'))window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
renderMenu();
