import {MAGES,ALL_CARDS,CARD_BY_ID} from './cards.js?v=0600';
import {cardMarkup,portrait} from './art.js?v=0600';
import {transferCard} from './progress.js?v=0600';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mountDeckEditor(root,{profile:p,save,notify,sound,inspect,heroes,recommend,changed}){
 const abort=new AbortController(),listen=(el,n,fn)=>el.addEventListener(n,fn,{signal:abort.signal});
 let selected=null,gesture=null,hold=null,suppress=0;
 const counts=()=>p.decks[p.selected].reduce((a,id)=>(a[id]=(a[id]||0)+1,a),{});
 const sort=cards=>cards.sort((a,b)=>p.sort==='alpha'?a.name.localeCompare(b.name,'es'):({monster:0,minion:1,rune:2,spell:3}[a.kind]-{monster:0,minion:1,rune:2,spell:3}[b.kind]||a.cost-b.cost||a.name.localeCompare(b.name,'es')));
 function tile(c,n,zone){return `<button class="editor-card" data-card="${c.id}" data-zone="${zone}" aria-label="${esc(c.name)}, ${n} ${zone==='deck'?'en mazo':'disponibles'}" aria-pressed="false">${cardMarkup(c)}<b class="editor-count">${n}</b></button>`}
 function draw(){const scrolls=[...root.querySelectorAll('.deck-cards')].map(e=>e.scrollTop),c=counts(),cards=ALL_CARDS.filter(x=>(p.owned[x.id]||0)>0&&[p.selected,'neutral'].includes(x.element));
 root.innerHTML=`<header class="editor-header"><div><small>WILD WIZARDS</small><h1>Tu mazo <span>${p.decks[p.selected].length}/20</span></h1></div><button class="editor-hero" data-editor="hero" aria-label="Cambiar mago del mazo">${portrait(p.selected)}<b>${MAGES[p.selected].name} ›</b></button></header><div class="editor-tools"><label>Ordenar <select aria-label="Ordenar cartas"><option value="type" ${p.sort==='type'?'selected':''}>Tipo</option><option value="alpha" ${p.sort==='alpha'?'selected':''}>Alfabético</option></select></label><button data-editor="recommend">Mazo recomendado</button></div><div class="editor-action" aria-live="polite"></div><section class="deck-panel deck-panel-main" data-zone="deck"><button class="deck-zone-heading" data-destination="deck"><span>EN TU MAZO</span><b>${p.decks[p.selected].length}/20 · máximo 2 copias</b><span class="drop-instruction">↑ Añadir aquí</span></button><div class="deck-cards" aria-label="Cartas en tu mazo">${sort(cards.filter(x=>c[x.id])).map(x=>tile(x,c[x.id],'deck')).join('')||'<p class="empty-deck">Arrastra cartas aquí para preparar tu mazo.</p>'}</div></section><section class="deck-panel deck-panel-collection" data-zone="collection"><button class="deck-zone-heading" data-destination="collection"><span>COLECCIÓN DISPONIBLE</span><b>${cards.reduce((n,x)=>n+(p.owned[x.id]||0)-(c[x.id]||0),0)} copias fuera del mazo</b><span class="drop-instruction">↓ Quitar del mazo</span></button><div class="deck-cards" aria-label="Cartas disponibles en tu colección">${sort(cards.filter(x=>(p.owned[x.id]||0)>(c[x.id]||0))).map(x=>tile(x,p.owned[x.id]-(c[x.id]||0),'collection')).join('')||'<p class="empty-deck">Todas tus copias están en el mazo.</p>'}</div></section><div class="deck-drag-ghost hidden" aria-hidden="true"></div>`;
 root.querySelectorAll('.deck-cards').forEach((e,i)=>e.scrollTop=scrolls[i]||0);selectionUI();
 }
 function selectionUI(){const bar=root.querySelector('.editor-action');root.querySelectorAll('[data-card]').forEach(b=>{const active=selected?.id===b.dataset.card&&selected.zone===b.dataset.zone;b.classList.toggle('chosen',active);b.setAttribute('aria-pressed',String(active))});bar.innerHTML=selected?`<span><b>${esc(CARD_BY_ID[selected.id].name)}</b><small>${selected.zone==='deck'?'Toca Colección para quitar una copia.':p.decks[p.selected].length===20?'Mazo lleno: toca una carta de arriba para intercambiar.':'Toca Mazo para añadir una copia.'}</small></span><button data-editor="details">Ver carta</button><button data-editor="cancel" aria-label="Cancelar carta seleccionada">×</button>`:'<span>Mantén y arrastra una carta entre las dos zonas.<small>También puedes tocarla y elegir Mazo o Colección.</small></span>'}
 function transfer(destination,replaceId){if(!selected)return;if(selected.zone===destination){notify('La carta ya está en esa zona.');return}if(transferCard(p,selected.id,destination,replaceId)){save();sound.play('select',p.selected);selected=null;draw();changed?.()}else notify(destination==='deck'&&p.decks[p.selected].length>=20?'Mazo lleno: suelta sobre una carta para intercambiar una copia.':'No quedan copias disponibles para añadir.');}
 listen(root,'change',e=>{if(e.target.matches('select')){p.sort=e.target.value;save();draw()}});
 listen(root,'click',e=>{if(Date.now()<suppress)return;const command=e.target.closest('[data-editor]')?.dataset.editor;if(command){if(command==='hero')heroes();if(command==='recommend')recommend();if(command==='details'&&selected)inspect(selected.id);if(command==='cancel'){selected=null;selectionUI()}return}const dest=e.target.closest('[data-destination]');if(dest){transfer(dest.dataset.destination);return}const b=e.target.closest('[data-card]');if(!b)return;if(selected?.zone==='collection'&&b.dataset.zone==='deck'&&p.decks[p.selected].length===20){transfer('deck',b.dataset.card);return}selected={id:b.dataset.card,zone:b.dataset.zone};selectionUI();});
 function drag(){if(!gesture||gesture.scrolling)return;gesture.drag=true;selected={id:gesture.id,zone:gesture.zone};selectionUI();const ghost=root.querySelector('.deck-drag-ghost');ghost.innerHTML=cardMarkup(CARD_BY_ID[gesture.id]);ghost.classList.remove('hidden');root.classList.add('is-dragging');moveGhost(gesture.x,gesture.y);try{root.setPointerCapture(gesture.pointer)}catch{}}
 function moveGhost(x,y){const ghost=root.querySelector('.deck-drag-ghost');ghost.style.left=x+'px';ghost.style.top=y+'px';root.querySelectorAll('.drop-ready').forEach(e=>e.classList.remove('drop-ready'));document.elementFromPoint(x,y)?.closest('.deck-panel')?.classList.add('drop-ready')}
 function cancel(){clearTimeout(hold);if(gesture)try{root.releasePointerCapture(gesture.pointer)}catch{}gesture=null;root.classList.remove('is-dragging');root.querySelector('.deck-drag-ghost')?.classList.add('hidden');root.querySelectorAll('.drop-ready').forEach(e=>e.classList.remove('drop-ready'))}
 listen(root,'pointerdown',e=>{const b=e.target.closest('[data-card]');if(!b||e.button!==0)return;const pane=b.closest('.deck-cards');gesture={id:b.dataset.card,zone:b.dataset.zone,pointer:e.pointerId,x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY,scroll:pane.scrollTop,pane,mouse:e.pointerType==='mouse',drag:false};hold=setTimeout(drag,220)});
 listen(window,'pointermove',e=>{const g=gesture;if(!g||g.pointer!==e.pointerId)return;g.x=e.clientX;g.y=e.clientY;if(!g.drag&&Math.hypot(g.x-g.sx,g.y-g.sy)>10){clearTimeout(hold);if(g.mouse)drag();else g.scrolling=true}if(g.scrolling){g.pane.scrollTop=g.scroll-(g.y-g.sy);e.preventDefault()}else if(g.drag){moveGhost(g.x,g.y);e.preventDefault()}});
 listen(window,'pointerup',e=>{const g=gesture;if(!g||g.pointer!==e.pointerId)return;if(g.drag){const target=document.elementFromPoint(e.clientX,e.clientY),zone=target?.closest('[data-zone]')?.dataset.zone,replaceId=target?.closest('[data-card]')?.dataset.card;suppress=Date.now()+400;cancel();if(zone)transfer(zone,replaceId);else notify('Suelta en Mazo o Colección. No se cambió ninguna carta.')}else{if(g.scrolling)suppress=Date.now()+400;cancel()}});
 listen(window,'pointercancel',cancel);
 draw();return ()=>{cancel();abort.abort()};
}
