import assert from 'node:assert/strict';
import {MAGES,CATALOG,ALL_CARDS,CARD_BY_ID,NEUTRALS,deckList} from './cards.js';
import {Duel,targetKey} from './engine.js';
import {freshProfile,normalize,validDeck,changeDeck,claim,purchase,settle,opponent,nextBoss,BOSSES,MILESTONES,saveProfile,loadProfile} from './progress.js';
import {validRemoteDeck,validAction,guestView,validView,flipTarget} from './network.js';
const results=[];function test(n,f){f();results.push(n)}
const target=(side=0,lane=0,slot=0)=>({side,lane,slot,kind:'unit'});
function game(){const d=new Duel(()=>.4);d.start('fire');return d}
test('20-card decks: 16 minions, max two copies, legal mana budgets',()=>{for(const e of Object.keys(MAGES)){const d=deckList(e);assert.equal(d.length,20);assert.equal(d.filter(c=>c.type==='minion').length,16);assert(validRemoteDeck(e,d.map(c=>c.id)));for(const c of CATALOG[e].filter(c=>c.type==='minion')){assert(c.atk+c.hp<=c.cost*2+(c.cost===1?1:0));if(c.cost===2)assert(c.atk+c.hp>=3&&c.atk+c.hp<=5);if(c.cost===3)assert(c.atk+c.hp>=5&&c.atk+c.hp<=7)}}});
test('Movement consumes one mana, prevents an attack, and resets next turn',()=>{const d=game(),u=d.summon(0,CATALOG.fire[2],target(),false);d.sides[0].mana=5;u.born=0;assert(d.move(0,0,0,target(0,2,1)));assert.equal(d.sides[0].mana,4);assert(!d.ready(0,2,u));assert.equal(d.moves(0,2,1).length,0);assert.equal(d.attackTargets(0,2,1).length,0);d.end();d.end();assert(d.ready(0,2,u));assert(d.moves(0,2,1).length)});
test('An attacker cannot move; invalid targets spend no mana',()=>{const d=game(),u=d.summon(0,CATALOG.fire[2],target(),false);u.born=0;d.sides[0].mana=5;assert(d.strike(0,0,0,{side:1,kind:'crystal',lane:0,slot:0}));assert.equal(d.moves(0,0,0).length,0);assert(!d.move(0,0,0,target(0,2)));assert.equal(d.sides[0].mana,5)});
test('Shield offense uses live barriers; healing offense uses actual healing',()=>{const d=game();const u=d.summon(0,CATALOG.wind[4],target(),false);u.shield=6;assert.equal(d.stats(0,0,u).atk,u.atk+3);u.shield=2;assert.equal(d.stats(0,0,u).atk,u.atk+1);const v=d.summon(1,{...CATALOG.fire[14],hp:30},target(1),false);d.sides[0].crystals[1].hp=28;d.effect(0,{fx:'healStrike',power:3},target(1));assert.equal(d.sides[0].crystals[1].hp,30);assert.equal(v.damage,2);d.effect(0,{fx:'shieldBurst',power:2},target(1));assert.equal(u.shield,0);assert.equal(v.damage,6)});
test('All 108 cards execute legally and charge their exact costs',()=>{for(const c of ALL_CARDS){const d=game();d.sides[0].mana=20;d.sides[0].hand=[c];d.summon(0,CATALOG.water[2],target(),false);d.summon(1,CATALOG.water[14],target(1),false);d.sides[0].lanes[0][0].damage=1;d.sides[0].crystals[1].hp=22;d.sides[0].grave=[CATALOG.fire[2]];const ts=d.targets(0,c);assert(d.canPlay(0,c),c.name);assert(d.play(0,0,ts[0]),c.name);assert.equal(d.sides[0].mana,20-c.cost,c.name)}});
test('Campaign advances every ten victories, gates at bosses, unlocks sequentially',()=>{const p=freshProfile();assert.deepEqual(p.unlocked,['fire']);assert(validDeck(p));for(let stage=0;stage<4;stage++){const boss=BOSSES[stage];for(let i=0;i<10;i++)settle(p,`${stage}-${i}`,true,{practice:false});assert.equal(p.trophies,boss.at);const enc=opponent(p);assert.equal(enc.boss,boss.at);const r=settle(p,'boss'+stage,true,enc);assert.equal(r.unlocked,boss.unlock);assert(p.unlocked.includes(boss.unlock));assert(validDeck(p,boss.unlock))}assert.equal(nextBoss(p).at,2500)});
test('Rewards and chests settle once, locked rewards cannot be claimed',()=>{const p=freshProfile();assert(!claim(p,150));const a=purchase(p,'welcome');assert(a);assert.equal(p.owned['neutral-0'],2);const coins=p.coins;assert(!purchase(p,'welcome'));assert.equal(p.coins,coins);p.coins=0;assert(!purchase(p,'stone'));assert.equal(p.coins,0);p.trophies=150;assert(claim(p,150));const snapshot=JSON.stringify(p);assert(!claim(p,150));assert.equal(JSON.stringify(p),snapshot);assert(settle(p,'one',true,{practice:false}));const saved=JSON.stringify(p);assert(!settle(p,'one',true,{practice:false}));assert.equal(JSON.stringify(p),saved)});
test('Deck editing enforces ownership, class, 20-card size and copy count',()=>{const p=freshProfile();assert(!changeDeck(p,'water-0',1));purchase(p,'welcome');assert(!changeDeck(p,'neutral-0',1));assert(changeDeck(p,p.decks.fire[0],-1));assert(!validDeck(p));assert(changeDeck(p,'neutral-0',1));assert(validDeck(p));assert(!changeDeck(p,'neutral-0',1));assert(validDeck(normalize(JSON.parse(JSON.stringify(p)))))});
test('Storage round trip, name escaping inputs and failure handling',()=>{const p=freshProfile();p.name='<Mago>';const storage={value:null,setItem(k,v){this.value=v},getItem(){return this.value}};assert(saveProfile(p,storage));assert.equal(loadProfile(storage).name,'<Mago>');assert.equal(loadProfile(storage).playerId,p.playerId);assert(!saveProfile(p,{setItem(){throw Error('quota')}}));assert(validDeck(loadProfile({getItem(){throw Error('blocked')}})))});
test('Private snapshot flips perspective and never sends the rival hand or decks',()=>{const d=game(),v=guestView(d,[{type:'damage',target:target(0,2),amount:1}]);assert(validView(v));assert.equal(v.sides[0].element,d.sides[1].element);assert(v.sides[1].hand.every(c=>c.hidden));assert(v.sides[0].deck.every(c=>c.hidden));assert.equal(v.active,1);assert.equal(v.events[0].target.side,1);assert.deepEqual(flipTarget(flipTarget(target())),target());assert(!validRemoteDeck('fire',Array(20).fill('fire-0')));assert(!validAction({type:'move',lane:99,slot:0}));assert(!validAction({type:'card',index:-1}));assert(!validAction({type:'power',target:{side:8,lane:0,slot:0,kind:'unit'}}))});
test('Full AI matches complete without negative mana or more than six units',()=>{for(const e of Object.keys(MAGES)){const d=new Duel(()=>.4);d.start(e);let turns=0;while(!d.over&&turns++<90){for(let n=0;n<35&&!d.over;n++){let a;if(d.active===1)a=d.aiChoice();else{const index=d.sides[0].hand.findIndex(c=>d.canPlay(0,c));if(index>=0)a={type:'card',index,target:d.targets(0,d.sides[0].hand[index])[0]};else{for(const t of d.units(0)){const ts=d.attackTargets(0,t.lane,t.slot);if(ts.length){a={type:'attack',...t,target:ts[0]};break}}}}if(!a)break;assert(d.act(a));for(const p of [0,1]){assert(d.sides[p].mana>=0);assert(d.units(p).length<=6)}}if(!d.over)d.end()}assert(d.over,e)}});
console.log(JSON.stringify({passed:results.length,tests:results},null,2));
